// 本文件为报告数据底稿，数字以 outline/数字校准表.md 为唯一权威
(function () {
  "use strict";

  window.RPT = {
    meta: {
      title: "AI 产业链：谁把稀缺的芯片和电力，变成了客户持续付费的服务",
      subtitle: "从 token 到任务：计量切换如何重写产业链的利润分配 · 交互研究报告",
      asof: "2026-07-17",
      asofLabel: "本报告数据截至 2026-07-17",
      footer: "每个读数可点击下钻到带日期的出处 · 无源不画 · 仅供参考，不构成投资建议",
      note: "本报告全部数字均为公开信息或基于公开信息的测算，可点击下钻查看口径与带日期的出处。",
    },

    // 封面关键数字带（五格，全部绑定下钻；自研读数带 base 情景、下钻第一屏为情景区间）
    // 键名 = index.html 封面 [data-kb] 的值（main.js count-up / dash.js 读数牌共用此契约）：
    // value 为 count-up 终点数值（区间用 [a,b]），display 为终值字符串，fmt 为 count-up 帧格式化（可含 HTML）。
    keyNumbers: {
      share: { id: "profitShare", value: 71.3, display: "71.3%", label: "利润池上游份额（base 情景）", scenario: "base 情景",
        fmt: v => v.toFixed(1) + "%",
        drill: { title: "利润池上游份额（本报告测算）", value: "base 情景 71.3%（走廊：悲观 80.4% / 乐观 60.5%）",
          sub: "把产业链上所有公司当季赚到的经营利润加在一起（正利润池 base $91.69B），半导体层分到 $65.33B。乐观情景（下游改善）下半导体仍有 60.5%——上游化在情景间稳健。",
          source: "本报告测算 · 2026-07-17" } },
      gap: { id: "gapRatio", value: 0.97, display: "0.97", label: "供需缺口比，起点 0.70（base 情景）", scenario: "base 情景",
        fmt: v => v.toFixed(2),
        drill: { title: "供需缺口比（本报告测算）", value: "base 情景 0.70→0.97（走廊：放松 0.34 / 收紧 2.27）",
          sub: "按需求和供给各自的增长速度折算出的比值——小于 1 表示供给还追得上（紧平衡），大于 1 表示越买越缺。缺口比小于 1 = 紧平衡，不等于短缺。结论翻转开关：中国模型租用服务一线增速砍半，结论立即翻转。",
          source: "本报告测算 · 2026-07-17" } },
      ds: { id: "demandSupply", value: [3.94, 2.85], display: "3.94x vs 2.85x", label: "需求与供给的年化增速（base 情景）", scenario: "base 情景",
        fmt: (a, b) => a.toFixed(2) + "x<span class=\"u\"> vs </span>" + b.toFixed(2) + "x",
        drill: { title: "需求 vs 供给年化增速（本报告测算）", value: "base 情景：需求 3.94x vs 供给 2.85x（收紧 6.22x/1.92x；放松 2.15x/4.40x）",
          sub: "需求侧由六条增长线按已披露锚点加权合成；供给侧 = 产能增速 1.9x × 服务速率增速 1.5x。需求仍快于供给，稀缺在加剧，但强度温和。",
          source: "本报告测算 · 2026-07-17" } },
      rev: { id: "revPool", value: 326, display: "$326B", label: "推理收入池（base 情景）", scenario: "base 情景",
        fmt: v => "$" + Math.round(v) + "B",
        drill: { title: "推理收入池（本报告测算）", value: "base 情景 $326B（走廊：悲观 $241B / 乐观 $411B）",
          sub: "走量档与前沿档两层价格 × 用量外推。已知局限：走量档有效价对中国补贴型模型租用服务偏贵，区间可能偏高 1.5–2 倍。",
          source: "本报告测算 · 2026-07-17" } },
      capex: { id: "capexGuide", value: [695, 725], display: "$695–725B", label: "四家超大规模云厂商 2026 年资本开支指引合计", scenario: "",
        fmt: (a, b) => "$" + Math.round(a) + "–" + Math.round(b) + "B",
        drill: { title: "2026 年资本开支指引合计（券商聚合口径）", value: "$695–725B，相当于较 2025 年 +93%~+101%（中值约翻倍）",
          sub: "公司披露现金口径 2025 年四家合计 $359.9B（+64%）；另有券商汇总口径 $412.9B（+68%，含融资租赁），差额约 $53B 几乎全部为 Microsoft 口径差。超大规模云厂商 = 微软、谷歌、亚马逊、Meta 四家。",
          source: "券商研究 · 2026-07-17" } },
    },

    // 封面主视觉：利润地层图（六层，面积编码 base 情景利润份额，模型层红色下凹）
    strata: [
      { id: "semiconductor", name: "半导体（GPU/高带宽内存/先进封装/设备）", shareBase: 71.3, valueBase: 65.33, negative: false,
        drill: { title: "半导体层", value: "base $65.33B/季（走廊：悲观 $59.33B / 乐观 $73.33B）",
          sub: "NVIDIA $49.33B（FY1Q27 数据中心收入 $75.2B、+92%，按全公司经营利润率折算）+ 其他 $16B（含 Broadcom AI $10.8B/季、+143%，以及高带宽内存/先进封装/设备估算）。",
          source: "官方披露 · 本报告测算 · 2026-07-17" } },
      { id: "cloud", name: "云/AI 算力", shareBase: 11.3, valueBase: 10.36, negative: false,
        drill: { title: "云/AI 算力层", value: "base $10.36B/季（走廊：悲观 $7.96B / 乐观 $13.81B）",
          sub: "Microsoft AI（年化收入 $37B 折算）+ AWS 自研芯片 + Google Cloud AI 份额 + AWS AI 服务。AI 业务的单独利润率各家均未披露，是最大敏感项。",
          source: "管理层口径 · 本报告测算 · 2026-07-17" } },
      { id: "dcpower", name: "数据中心/电力/液冷", shareBase: 8.7, valueBase: 8.0, negative: false,
        drill: { title: "数据中心/电力/液冷层", value: "base $8B/季（走廊：悲观 $4B / 乐观 $13B）",
          sub: "GE Vernova 在手订单 $163B、伊顿数据中心在手订单约等于 12 年建设量、Vertiv 在手订单 +80.8%、CoreWeave 在手订单 $99.4B（约 47.8 倍季度收入）。",
          source: "官方披露 · 券商研究 · 2026-07-17" } },
      { id: "workflow", name: "工作流软件", shareBase: 6.5, valueBase: 6.0, negative: false,
        drill: { title: "工作流软件层", value: "base $6B/季（走廊：悲观 $2B / 乐观 $12B）",
          sub: "Salesforce Agentforce 年化收入 $1.2B（+205%）、ServiceNow 年度合同额目标上调至 $1.5B、Adobe AI 优先产品年化收入 >$500M、Copilot 付费席位 2,000 万+。渗透率警示：Agentforce 付费客户约占客户基数 6%。",
          source: "官方披露 · 本报告测算 · 2026-07-17" } },
      { id: "services", name: "服务/集成", shareBase: 2.2, valueBase: 2.0, negative: false,
        drill: { title: "服务/集成层", value: "base $2B/季（走廊：悲观 $0.5B / 乐观 $5B）",
          sub: "企业落地服务的收入 × 利润率情景；规模和可持续性弱于软件与上游。",
          source: "本报告测算 · 2026-07-17" } },
      { id: "modellab", name: "模型/接口层（净利润口径）", shareBase: -5.8, valueBase: -5.0, negative: true,
        drill: { title: "模型/接口层净利润（本报告测算）", value: "base −$5B/季，按净利润池口径 −5.8%（走廊：悲观 −19.4% / 乐观 +3.3%）",
          sub: "分母为净利润池（base $86.69B），与正值层的正利润池口径不同。OpenAI 2025 年经营亏损 −$20.92B（审计报道口径）；Anthropic 年化收入 $47B（管理层口径，未经审计）。模型层创造需求，尚未证明留存利润。",
          source: "媒体报道与访谈 · 本报告测算 · 2026-07-17" } },
    ],

    // §0 三年事件墙（9 块事件牌）
    timeline: [
      { y: "2023", label: "生成式 AI 点火", kind: "ink",
        drill: { title: "2023 · 点火", value: "ChatGPT 后两个季度 NVIDIA 数据中心收入环比 +141%",
          sub: "NVIDIA 数据中心收入 2023 年一季度 $4.28B → 2026 年一季度 $75.2B，13 个季度 17.6 倍。", source: "官方披露 · 2023-05" } },
      { y: "2024", label: "高带宽内存成为第一瓶颈", kind: "ink",
        drill: { title: "2024 · 内存瓶颈", value: "SK hynix 2024 年高带宽内存全部售罄",
          sub: "三家寡头 + 代际转换的晶圆损耗，无绕行路线；高带宽内存占 DRAM 收入升至约五分之二（2026 年预期）。", source: "官方披露 · 2024-05" } },
      { y: "2025-08", label: "GPT-5 旗舰价格谷底", kind: "ink",
        drill: { title: "2025-08 · 价格谷底", value: "GPT-5 定价 $1.25/$10（每百万 token 输入/输出）",
          sub: "市场一度认为模型价格崩了；TechCrunch 评'定价低到可能挑起价格战'。此后旗舰价 V 形反转。", source: "官方披露 · 2025-08" } },
      { y: "2025-10", label: "基础设施承诺潮", kind: "ink",
        drill: { title: "2025-10 · 承诺潮", value: "OpenAI 10GW 定制加速器框架（Broadcom）",
          sub: "Anthropic 5GW、Meta 3GW（Broadcom 电话会）；OpenAI 累计承诺约 $1.4 万亿（券商汇总）。产能承诺不等于现金资本开支。", source: "官方披露 · 券商研究 · 2025-10" } },
      { y: "2025-11", label: "纳德拉改口：芯片插不上电", kind: "ink",
        drill: { title: "2025-11 中旬 · 第四棒现身", value: "'warm shells'——没有通了电可以插的机房",
          sub: "微软 CEO 纳德拉在 BG2 播客公开承认芯片躺在库存里插不上电：电力取代芯片成为新约束。", source: "官方披露 · 2025-11" } },
      { y: "2026-04", label: "DeepSeek 折扣长期化 · 阿里 token 暴涨", kind: "ink",
        drill: { title: "2026-04 · 中国价格与量", value: "缓存命中价永久降为原价 1/10；百炼 token 3 个月 6 倍",
          sub: "DeepSeek 牌价涨、实付稳，守住最低价档；阿里日均 token 收入较 4 月初 +5 倍。", source: "官方披露 · 2026-04" } },
      { y: "2026-06", label: "前沿模型首次被行政令下架", kind: "brk",
        drill: { title: "2026-06 · 模型层管制首例", value: "Anthropic 两个新模型全球停售 06-12 → 07-01，共 19 天",
          sub: "前沿模型首次被行政令直接中断全球供给——'生产力单元的跨境结算'从此有了先例。", source: "官方披露 · 2026-06" } },
      { y: "2026-07-16", label: "台积电法说会：封装严重供不应求", kind: "cur",
        drill: { title: "2026-07-16 · 台积电法说会", value: "资本开支上调至 $60–64B；'severely supply-constrained'",
          sub: "魏哲家：后段封装已成为限制客户成长的瓶颈；2029–2030 年前需求持续强劲。", source: "官方披露 · 2026-07-16" } },
      { y: "2026-07-16/17", label: "中国旗舰模型集体提价", kind: "cur",
        drill: { title: "2026-07-16/17 · 集体提价", value: "Kimi K3 $3/$15 = K2 输入价的 5 倍；Qwen 约 2 倍；GLM 年内三次调价",
          sub: "追赶前沿的代价是守不住价格；DeepSeek 靠长期折扣独守最低价档。", source: "官方披露 · 2026-07-17" } },
    ],

    // §0 三线叙事主线图（图上文字：本报告的一把尺子：任务计量 / 供需缺口测算）
    mainlines: {
      ruler: "本报告的一把尺子：任务计量（token → 任务）",
      main: { name: "主线 · 任务经济（需求侧）", nodes: [
        { chapter: "§1", title: "任务通胀", desc: "需求是真的" },
        { chapter: "§2", title: "计量战争", desc: "单位是战场" },
        { chapter: "§3", title: "定价两层", desc: "价格分两层" },
        { chapter: "§4", title: "变现证据", desc: "谁按任务收到钱" },
      ] },
      hub: { chapter: "§5", title: "供需缺口测算", desc: "需求 3.94x vs 供给 2.85x → 缺口比 0.70→0.97（base 情景）" },
      branchA: { name: "副线 · 瓶颈接力（物理侧）", chapters: "§6–§7", desc: "GPU→高带宽内存→先进封装→电力：供给为什么追不上" },
      branchB: { name: "副线 · 资产负债表战争（资金侧）", chapters: "§8", desc: "$695–725B 资本开支 · 发债 $159B：钱从哪来、哪里最脆" },
      merge: { chapter: "§9", title: "三线汇合：利润池瀑布", desc: "半导体 71.3% · 云 11.3% · 数据中心/电力 8.7% · 工作流软件 6.5% · 服务 2.2% · 模型层 −5.8%（均为 base 情景）" },
      mirrors: [
        { chapter: "§10", title: "中国链", desc: "任务计量在国产替代约束下的映照" },
        { chapter: "§11", title: "出口管制", desc: "'可结算'的地缘边界" },
      ],
      verdict: [
        { chapter: "§12", title: "裁决与反证", desc: "八架天平，八条红线" },
        { chapter: "§13", title: "总结：结论与方向", desc: "叙事收束 + 六条结论 + 投资方向" },
      ],
    },

    // §1 任务强度谱系对数阶梯（10³→10¹⁰ 六档；"有效强度/含浪费总强度"双列切换）
    taskSpectrum: {
      toggle: { effective: "有效强度", gross: "含浪费总强度", wasteNote: "生产环境 token 浪费率 30–72%（《财经》2026-04-16 实测 72%）；含浪费总强度 = 有效强度 ÷（1 − 浪费率）。" },
      wasteMath: "浪费率从 70% 压到 20%，会使总强度乘数从 1.7 降到 1.2；只有当有效需求涨幅低于约四成（1.7/1.2）时，总消耗才会下降。",
      tiers: [
        { id: "chat", label: "日常对话", tokens: "<10³", logMin: 0, logMax: 3,
          drill: { title: "日常对话", value: "不到 1 千 token/次",
            sub: "双平台实测口径。token 是 AI 计费的最小单位，约相当于一个英文单词片段或一两个汉字。", source: "媒体报道与访谈 · 2026-05-25" } },
        { id: "doc", label: "单篇文档", tokens: "~5×10³", logMin: 3, logMax: 4,
          drill: { title: "单篇文档处理", value: "约 5 千 token/次",
            sub: "读写完一整篇文档的量级。", source: "媒体报道与访谈 · 2026-05-25" } },
        { id: "deepread", label: "多文档深读", tokens: "~10⁵", logMin: 4, logMax: 5,
          drill: { title: "多文档深读", value: "约 10 万 token/次",
            sub: "例如同时深读 24 个季度的财报。", source: "媒体报道与访谈 · 2026-05-25" } },
        { id: "agent", label: "多步智能体任务", tokens: "10⁵–10⁶", logMin: 5, logMax: 6,
          drill: { title: "多步智能体任务", value: "单个智能体任务 ≈ 4 倍对话；多智能体 ≈ 15 倍对话",
            sub: "AI 智能体 = 能自动连续执行多步任务的 AI。Anthropic 工程博客：token 用量解释任务表现方差的 80%。", source: "官方披露 · 2025-06" } },
        { id: "coding", label: "自动编程任务", tokens: "10⁶–10⁷", logMin: 6, logMax: 7,
          drill: { title: "自动编程任务", value: "单轮问答的 3,500 倍、多轮代码聊天的 1,200 倍",
            sub: "同一任务不同次运行方差最高 30 倍。来源为斯坦福学术论文（2026-04，arXiv:2604.22750）——单一研究、单一基准（OpenHands × SWE-bench-verified），且与旧数据集跨基线比较，引用须注明。", source: "券商研究 · 2026-04" } },
        { id: "build", label: "应用构建", tokens: "10⁸–4×10⁹", logMin: 8, logMax: 9.6,
          drill: { title: "应用构建", value: "搭一个小型网页应用约 1 亿 token；一位研究员三周搭建工作流消耗 40 亿 token",
            sub: "完成一个任务要消耗的算力横跨 7 个数量级：日常对话不到 1 千，搭建一个应用上亿。", source: "媒体报道与访谈 · 2026-06-05" } },
      ],
    },

    // §1 员工级强度大数字卡 + B 面
    intensity: {
      cards: [
        { value: "1,000 万–3 亿", label: "一线员工日均 token 消耗", drill: { title: "员工级强度", value: "1,000 万–3 亿 token/日",
          sub: "产研高强度岗位 5 亿+/日；某 30 万员工巨头的工程师周 token 成本 $2,000–3,000。", source: "媒体报道与访谈 · 2026-06" } },
        { value: "$1,500/人/月", label: "Uber 设的 AI 使用上限", drill: { title: "Uber 预算上限", value: "4 个月烧完全年 AI 预算，随后设 $1,500/人/月上限",
          sub: "重度用户 $500–2,000/月。", source: "媒体报道与访谈 · 2026-06-02" } },
        { value: "7,000 万/天", label: "重度编程智能体用户实测", drill: { title: "一线实测样本", value: "约 7,000 万 token/天，约为普通用户平均假设的 10 倍",
          sub: "用量呈幂律分布：少数重度用户消耗了绝大部分算力，不能用平均值推算。", source: "媒体报道与访谈 · 2026-07-17" } },
      ],
      waste: { rate: "30–72%", entelligence: "每 $1 token 费用仅 18 美分触达终端价值（2,444 家企业汇总）",
        note: "token 多 ≠ 成功率高：斯坦福同文 B 面显示准确率在中等成本见顶。",
        drill: { title: "B 面：浪费率", value: "生产环境 token 浪费率 30–72%（2026-04-16 实测 72%）",
          sub: "浪费率大幅压缩且有效需求涨幅低于约四成 → 总消耗下降。这是本章判断的失效条件。", source: "媒体报道与访谈 · 券商研究 · 2026-04-16" } },
    },

    // §2 计量战争：三层站位矩阵 + 历史先例六锚
    metering: {
      tiers: [
        { id: "usage", name: "按量付费", desc: "底层：按 token/点数结算",
          players: [
            { name: "GitHub Copilot", price: "订阅改按 AI 点数计费（$0.01/点数）", date: "2026-04-27 宣布、06-01 生效", status: "官方",
              note: "官方解释改制理由（转述）：轻量问答与数小时长任务同价难以为继。" },
            { name: "OpenAI/Anthropic/Google API", price: "按 token 计价", date: "长期", status: "官方", note: "底层默认形态。" },
          ] },
        { id: "task", name: "按任务量计费", desc: "中层：按完成的任务/动作结算",
          players: [
            { name: "Salesforce Agentforce", price: "每个动作 $0.10", date: "2025 起", status: "官方",
              note: "把一次完成的 AI 任务记为一个任务量单位。" },
            { name: "Intercom Fin", price: "$0.99/次解决", date: "待核", status: "待核", note: "券商研究转述，未独立核验。" },
            { name: "Zendesk", price: "$1.50–2.00/次核实解决", date: "待核", status: "待核", note: "券商研究转述，未独立核验。" },
            { name: "Sierra", price: "纯按结果计费，年化收入超 $1 亿", date: "待核", status: "待核", note: "券商研究转述，未独立核验。" },
          ] },
        { id: "seat", name: "席位捆绑", desc: "顶层：按人/月打包",
          players: [
            { name: "Microsoft 365 E7", price: "$99/席/月", date: "2026-05-01 上线", status: "官方",
              note: "'实际仅省约 3% 而非宣称 15%'为券商研究口径，待核。" },
            { name: "Copilot Chat", price: "并入基础套件", date: "2026-07-01", status: "官方", note: "席位制未死，反在扩编。" },
          ] },
      ],
      futurum: { n: 830, outcome: "按结果计费偏好 21.7% vs 席位 20.1%——持平未逆转",
        caveat: "偏好口径非实际采用；同机构其他口径给出 30%/43% 偏好按量计费，读数对问卷措辞高度敏感。Agentforce 订单 60%+ 仍来自老客户席位扩张。",
        source: "券商研究 · 2026-06" },
      drift: { text: "Salesforce token 环比 +152% 快于任务量单位 +111%，边际汇率在漂移，且任务量单位口径曾扩围。",
        source: "官方披露 · 2026-05-27" },
      precedents: [
        { year: "1897", name: "两部制电价", event: "芝加哥爱迪生：容量费 + 电量费", lesson: "计量方式本身就是定价权。", drill: { title: "1897 · 两部制电价", value: "容量费 + 电量费", sub: "最早的'保底 + 按量'混合计费。", source: "媒体报道与访谈 · 史料" } },
        { year: "1959", name: "施乐按张计费", event: "$95/月 + 超量每张 4 美分", lesson: "按任务收费让复印机三年收入 $40M→$400M。", drill: { title: "1959 · 施乐", value: "三年收入 $40M→$400M", sub: "按张计费降低了采用门槛，同时把定价权留在了厂商手里。", source: "媒体报道与访谈 · 史料" } },
        { year: "1968", name: "分时服务局消亡", event: "GE 占分时计算服务 40%", lesson: "按机时出租算力的生意被自有设备取代。", drill: { title: "1968 · 分时服务局", value: "GE 占 40% 份额", sub: "算力租赁的第一代形态，随设备普及而消亡。", source: "媒体报道与访谈 · 史料" } },
        { year: "1996", name: "AOL 包月", event: "$19.95 包月不限时", lesson: "包月引爆需求，也引来网络拥塞。", drill: { title: "1996 · AOL 包月", value: "$19.95/月", sub: "不限量包月快速普及了互联网，但成本失控。", source: "媒体报道与访谈 · 史料" } },
        { year: "2017", name: "MoviePass", event: "$9.95/月，月均 2.11 部即必亏", lesson: "补贴型包月的数学边界。", drill: { title: "MoviePass", value: "月均看 2.11 部即必亏", sub: "定价低于成本曲线的包月，用户越忠诚亏得越快。", source: "媒体报道与访谈 · 史料" } },
        { year: "2017→2026", name: "电信流量包月悔意", event: "Verizon 2017 不限量 → Airtel 2026 称'定价架构坏了'", lesson: "不限量套餐在流量通胀下反噬运营商。", drill: { title: "电信包月悔意", value: "'定价架构坏了'（Airtel 2026）", sub: "与今天 $200 包月拉满用的处境同构。", source: "媒体报道与访谈 · 2026" } },
      ],
    },

    // §2 订阅补贴对照卡（标注 SemiAnalysis 测算口径）
    subsidy: {
      cards: [
        { value: "$14,000/月", label: "$200/月 ChatGPT Pro 拉满使用的 API 等效（约 70 倍）" },
        { value: "$8,000/月", label: "Claude Max 拉满使用的 API 等效（约 40 倍）" },
        { value: "5.7%", label: "最高档利用率约 5.7% 即零毛利" },
        { value: "10% / 11.4%", label: "Anthropic 最高档 / Plus/Pro 5x 档的零毛利利用率" },
      ],
      note: "SemiAnalysis 2026-06 测算口径：标价不等于成本，真实补贴深度必小于 70 倍，属其测算口径下的理论上限。",
      drill: { title: "订阅补贴的量化（媒体测算）", value: "$200/月 ≈ $14,000/月 API 等效（理论上限 70 倍）",
        sub: "零毛利利用率阈值：约 5.7%（最高档）。标价不等于成本，真实补贴深度必小于 70 倍。", source: "媒体报道与访谈 · 2026-06" },
    },

    // §3 对数轴旗舰价格 V 形折线（输入价 $/百万 token；发布日未核验者不标日期）
    frontierPrice: [
      { date: "2024-05", label: "GPT-4o", price: 5, tier: "frontier", drill: { title: "GPT-4o", value: "$5/$15", sub: "上一代旗舰定价基准。", source: "官方披露 · 2024-05" } },
      { date: "2024-09", label: "o1-preview", price: 15, tier: "reasoning", drill: { title: "o1-preview", value: "$15/$60", sub: "推理档开创：推理 token 开始计费。", source: "官方披露 · 2024-09" } },
      { date: "2025-02", label: "GPT-4.5", price: 75, tier: "frontier", drill: { title: "GPT-4.5", value: "$75/$150", sub: "短命旗舰，2025-07 被 GPT-4.1 取代下线。", source: "官方披露 · 2025-02" } },
      { date: "2025-03", label: "o1-pro（历史峰值）", price: 150, tier: "super", drill: { title: "o1-pro", value: "$150/$600", sub: "API 历史峰值。", source: "官方披露 · 2025-03" } },
      { date: "2025-06", label: "o3-pro", price: 20, tier: "super", drill: { title: "o3-pro", value: "$20/$80", sub: "天花板自峰值回落约 87%。", source: "官方披露 · 2025-06" } },
      { date: "2025-08", label: "GPT-5（旗舰谷底）", price: 1.25, tier: "frontier", drill: { title: "GPT-5", value: "$1.25/$10", sub: "旗舰价格谷底——市场一度认为价格崩了。GPT-4 发布价 $30 → GPT-5 $1.25，29 个月 24 倍。", source: "官方披露 · 2025-08" } },
      { date: "2025-11", label: "Claude Opus 4.5", price: 5, tier: "frontier", drill: { title: "Claude Opus 4.5", value: "$5/$25", sub: "官方口径'降价 67%'（对比 Opus 4 的 $15/$75）。", source: "官方披露 · 2025-11" } },
      { date: "2026-02", label: "Opus 4.6 Fast", price: 30, tier: "super", drill: { title: "Claude Opus 4.6 Fast", value: "$30/$150", sub: "Anthropic 在常规旗舰之上的速度档。", source: "官方披露 · 2026-02" } },
      { date: "2026-04", label: "Mythos Preview（受限）", price: 25, tier: "super", drill: { title: "Mythos Preview", value: "$25/$125", sub: "Anthropic 在 Opus 之上新开超档（受限开放）。", source: "券商研究 · 2026-04" } },
      { date: "2026-04", label: "GPT-5.5 Pro（当前峰值）", price: 30, tier: "super", drill: { title: "GPT-5.5 Pro", value: "$30/$180", sub: "当前在售旗舰最高挂牌。同日 GPT-5.5 $5/$30。", source: "官方披露 · 2026-04" } },
      { date: "2026-07", label: "GPT-5.6 Sol", price: 5, tier: "frontier", drill: { title: "GPT-5.6 Sol", value: "$5/$30", sub: "2026-07-09 正式开放；按输入价为谷底 4 倍、按输出价 3 倍。Terra $2.50/$15（发布日未核验，不标日期）、Luna $1/$6。", source: "官方披露 · 2026-07-09" } },
    ],
    frontierExtras: {
      ladder: "价格梯子向两端拉长：输入价口径 600 倍（$0.05→$30），输出价口径 450 倍（$0.40→$180）。",
      volumeHike: { label: "Google Flash 档（走量档提价）", points: [
        { tag: "起点", price: 0.3, output: 2.5 }, { tag: "中间", price: 0.5, output: 3 },
        { tag: "2026-05-19", label: "Gemini 3.5 Flash", price: 1.5, output: 9 } ],
        note: "输入价 11 个月 5 倍，为全场最大涨幅。", source: "官方披露 · 2026-05-19" },
      hiddenHike: { sonnet: "Claude Sonnet 5（2026-06-30）新分词器使同样文本多产出 1.0–1.35 倍 token",
        gemini: "Gemini 3.5 Flash 跑同一评测花 $1,551 vs 前代 Pro $892（Simon Willison 实测）",
        source: "媒体报道与访谈 · 2026-06-30" },
    },

    // §3 中国厂商阶梯双线（Kimi 阶梯 + DeepSeek 牌价/实付落差 + Qwen）
    chinaFrontier: {
      kimi: [
        { date: "2025-07", label: "Kimi K2", price: 0.6, drill: { title: "Kimi K2", value: "$0.60/$2.50", sub: "中国前沿定价起点。", source: "官方披露 · 2025-07" } },
        { date: "2026-04-20", label: "Kimi K2.6", price: 0.95, drill: { title: "Kimi K2.6", value: "$0.95/$4.00（+58%）", sub: "开始提价。", source: "官方披露 · 2026-04-20" } },
        { date: "2026-07-16/17", label: "Kimi K3", price: 3.0, drill: { title: "Kimi K3（2.8T 参数）", value: "$3/$15 = K2 输入价的 5 倍、输出价的 6 倍",
          sub: "全球参数最大开源权重模型；追赶前沿的代价是守不住价格。K3 仍只有 GPT-5.6 Sol 的六成、Anthropic 新一代旗舰的三成。", source: "官方披露 · 2026-07-17" } },
      ],
      qwen: [
        { date: "2025-09", label: "Qwen3-Max", price: 1.2, drill: { title: "Qwen3-Max", value: "$1.2/$6", sub: "", source: "官方披露 · 2025-09" } },
        { date: "2026-05", label: "Qwen3.7-Max", price: 2.5, drill: { title: "Qwen3.7-Max", value: "$2.50/$7.50（约 2 倍）", sub: "转闭源。", source: "官方披露 · 2026-05" } },
      ],
      deepseek: { label: "DeepSeek V4 Pro", list: 1.74, listOutput: 3.48, effective: 0.435, effectiveOutput: 0.87,
        drill: { title: "DeepSeek V4 Pro", value: "牌价 $1.74/$3.48 → 实付 $0.435/$0.87",
          sub: "唯一结构性例外：牌价涨 6 倍，靠长期 75 折稳实付；2026-04-26 缓存命中价永久降为原价 1/10。官方称国产芯片量产后还将大幅降价。", source: "官方披露 · 2026-04-26" } },
      note: "GLM 年内三次调价。中国厂商集体提价，仅 DeepSeek 以'牌价涨、实付稳'守住最低价档。",
    },

    // §3 走量档/前沿档参数卡
    priceTier: {
      volume: { name: "走量档", list: 1.5, discount: "0.3–0.7", change12m: "年降 60–80%", elasticity: "1.2–1.8",
        note: "DeepSeek 实付 / Flash / nano / Luna。Jevons 效应成立——用得越便宜、用得越多，总支出反而不降（19 世纪经济学家在煤炭上发现的现象）：量升价跌，收入池持平。" },
      frontier: { name: "前沿档", list: 12, discount: "0.6–0.9", change12m: "−20%~+50%", elasticity: "0.8–1.2",
        note: "GPT-5.5/5.6、Fable/Mythos、K3、Qwen-Max。V 形反转后量价齐升。" },
    },

    // §3 收入池走廊 + 自校验
    revenuePool: {
      corridor: { low: 240.8, base: 325.9, high: 411.0, display: "$241B / $326B / $411B（悲观/基准/乐观）" },
      selfCheck: {
        volume: { from: 99.6, to: 105.8, note: "走量档 12 个月：$99.6B → $105.8B——量升价跌对冲，Jevons 效应成立。" },
        frontier: { from: 226, to: 1365.8, note: "前沿档按'用量 8 倍 + 价格持平'外推：$226B → $1.366 万亿。" },
        verdict: "本报告判断此处必有一错：要么编程智能体用量增速下台阶，要么前沿档价格扛不住。两个方向的证据已在反证部分列出。",
      },
      reconcile: "可识别锚点合计（OpenAI 年化 $25B、Anthropic 年化 $47B、Microsoft AI 年化 $37B、Exponential View $175B 不含中国）约 $150–200B+——base $326B 偏高 1.5–2 倍，主因走量档有效价对中国补贴型模型租用服务偏贵。",
      drill: { title: "收入池走廊（本报告测算）", value: "base $326B（走廊 $241B–$411B）",
        sub: "已知局限：区间可能偏高 1.5–2 倍。自校验警示：前沿档外推 $226B→$1.366 万亿不可能成立。", source: "本报告测算 · 2026-07-17" },
    },

    // §4 AI 收入口径三层分层图（20 行同口径证据；官方披露 vs 媒体测算分色）
    skuEvidence: {
      tiers: ["单独定价并核算", "受 AI 带动但未单独计费", "无披露"],
      tierNote: "单独定价的 AI 产品 = 能明确归因到一个独立 AI 产品的收入，区别于'受 AI 带动但未单独计费的收入'。口径分层本身就是证据。",
      rows: [
        { company: "Salesforce", product: "Agentforce", tier: "单独定价并核算", value: "年化收入 $1.2B（同比 +205%）",
          detail: "2026 财年 Q1（截至 2026-04-30）；与 Data 360 合并年化收入约 $3.4B；累计 38 亿任务量单位（环比 +111%）、28.6 万亿 token（环比 +152%）。注：本报告利润池测算对该产品按 $1B 保守口径取值，两口径并列。", source: "官方披露 · 2026-05-27", official: true },
        { company: "Salesforce", product: "Agentforce + Data 360", tier: "单独定价并核算", value: "合并年化收入约 $3.4B", detail: "同上财季口径。", source: "官方披露 · 2026-05-27", official: true },
        { company: "ServiceNow", product: "Now Assist", tier: "单独定价并核算", value: "2026 年年度合同额目标上调至 $1.5B（自 $1.0B）",
          detail: "$1M+ 年度合同额客户同比 +130%；续费率 97%。", source: "官方披露 · 2026-04", official: true },
        { company: "Microsoft", product: "整体 AI 业务", tier: "单独定价并核算", value: "年化收入 $37B（同比 +123%）",
          detail: "管理层口径的年化收入。", source: "管理层口径 · 2026-04", official: true },
        { company: "Microsoft", product: "M365 Copilot", tier: "受 AI 带动但未单独计费", value: "付费席位超 2,000 万（同比约 +250%）",
          detail: "媒体测算隐含席位收入约 $7.2B 年化（测算口径，非公司披露）。", source: "媒体报道与访谈 · 2026-06", official: false },
        { company: "Adobe", product: "AI 优先产品", tier: "单独定价并核算", value: "年化收入 >$500M（约 3 倍）",
          detail: "Acrobat AI 助手约 3 倍。", source: "官方披露 · 2026-06", official: true },
        { company: "Adobe", product: "Firefly", tier: "单独定价并核算", value: "年化收入接近 $300M", detail: "", source: "官方披露 · 2026-06", official: true },
        { company: "Workday", product: "AI 产品", tier: "单独定价并核算", value: "年化收入接近 $500M",
          detail: "智能体 AI 新签年度合同额同比 +200%；4,000+ 客户在用至少 1 个智能体；超 50% 交易含 AI 组件。", source: "官方披露 · 2026-06", official: true },
        { company: "阿里云", product: "AI 相关产品", tier: "单独定价并核算", value: "季度收入 89.71 亿元（占云外部商业化收入 30%）",
          detail: "连续 11 个季度三位数增长（2026 财年 Q4）。", source: "官方披露 · 2026-05", official: true },
        { company: "阿里云", product: "AI 年化收入（含百炼）", tier: "单独定价并核算", value: "年化 >358 亿元，其中模型租用服务（百炼）年化 >80 亿元",
          detail: "中国口径最清晰的单独定价 AI 产品。模型租用服务 = 按调用量付费的 AI 模型服务。", source: "官方披露 · 2026-05", official: true },
        { company: "科大讯飞", product: "星火 API 及模型租用服务", tier: "单独定价并核算", value: "收入 3.85 亿元（同比 +263%）",
          detail: "", source: "官方披露 · 截至 2026-07-17", official: true },
        { company: "Anthropic", product: "Claude Code", tier: "单独定价并核算", value: "年化收入 $2.5B",
          detail: "$1M+ 客户超 1,000、两月翻倍（Reuters 2026-02）。", source: "媒体报道与访谈 · 2026-02", official: false },
        { company: "腾讯", product: "AI 新品（成本侧）", tier: "受 AI 带动但未单独计费", value: "AI 新品拖累单季经营利润约 88 亿元",
          detail: "剔除 AI 新品 844 亿 +17% vs 含 AI 756 亿 +9%。", source: "官方披露 · 截至 2026-07-17", official: true },
        { company: "Palantir", product: "AIP", tier: "受 AI 带动但未单独计费", value: "收入同比 +85%",
          detail: "增速对比用；未单独披露 AI 产品收入。", source: "媒体报道与访谈 · 日期待核", official: false },
        { company: "金山办公", product: "WPS AI", tier: "无披露", value: "月活 8,013 万（+307%），无 AI 单独收入",
          detail: "使用量不等于收入。", source: "官方披露 · 截至 2026-07-17", official: true },
        { company: "SAP", product: "—", tier: "无披露", value: "'仍处早期'", detail: "", source: "官方披露 · 截至 2026-07-17", official: true },
        { company: "Oracle", product: "—", tier: "无披露", value: "AI 收入集中在云基建，应用层无单列产品", detail: "", source: "官方披露 · 截至 2026-07-17", official: true },
        { company: "HubSpot", product: "—", tier: "无披露", value: "未披露单独定价的 AI 产品收入", detail: "", source: "官方披露 · 截至 2026-07-17", official: true },
        { company: "Zoom", product: "—", tier: "无披露", value: "未披露单独定价的 AI 产品收入", detail: "", source: "官方披露 · 截至 2026-07-17", official: true },
        { company: "monday", product: "—", tier: "无披露", value: "未披露单独定价的 AI 产品收入", detail: "", source: "官方披露 · 截至 2026-07-17", official: true },
      ],
      growthStrip: [
        { name: "Agentforce", growth: "+205%" }, { name: "科大讯飞星火", growth: "+263%" },
        { name: "微软 AI 业务", growth: "+123%" }, { name: "Palantir", growth: "+85%" },
      ],
    },

    // §4 单位任务毛利桥（双桥对照；成本假设随图注全列，可复算）
    grossBridge: {
      agentforce: {
        name: "Agentforce（按任务计费）", unit: "$/任务",
        scenarios: [
          { name: "乐观收入", revenue: 0.8, cost: 0.75, gm: "+6.3%", profit: "+$0.05B" },
          { name: "基准", revenue: 0.4, cost: 0.75, gm: "−87.5%", profit: "−$0.70B" },
          { name: "悲观收入", revenue: 0.16, cost: 0.1125, gm: "+29.7%", profit: "+$0.24B" },
        ],
        assumptions: "收入侧 = 年化收入 $0.8B ÷ 年任务量 1.0/2.0/5.0B（任务量为假设，随图注披露）；成本侧 $0.75/$0.75/$0.1125——悲观收入情景换用更便宜的模型组合与更高成功率。年利润近似值 = $0.8B × 毛利率。",
        source: "本报告测算 · 2026-07-17",
      },
      servicenow: {
        name: "ServiceNow（席位 + 增量对照）", unit: "$B/年",
        scenarios: [
          { name: "悲观", revenue: 0.37, gm: "40%", profit: "+$0.15B" },
          { name: "基准", revenue: 0.92, gm: "60%", profit: "+$0.55B" },
          { name: "乐观", revenue: 1.84, gm: "75%", profit: "+$1.38B" },
        ],
        assumptions: "收入近似值 = 年度合同额基数 $14.684B × 2.5%/6.25%/12.5%；毛利率 40%/60%/75%。",
        source: "本报告测算 · 2026-07-17",
      },
      note: "'收到钱'≠'赚到钱'：基准情景下单位任务毛利 −87.5%。只有记录系统级工作流 + 低复核成本 + 高成功率 + 明确付费单位同时成立，应用层才留得住毛利。",
    },

    // §4 任务成本对数轴全景（按官方牌价）
    taskCost: {
      points: [
        { label: "简单客服任务（最便宜档）", cost: 0.0004, note: "$0.0004/任务" },
        { label: "旗舰模型多步智能体任务（基准）", cost: 2.5, note: "约 $2.5/任务" },
        { label: "高开销组合（旗舰 + 长链条）", cost: 25, note: "可到 $25/任务" },
      ],
      span: "横跨 5 个数量级",
      drill: { title: "任务成本篮（本报告测算）", value: "$0.0004 → $25，横跨 5 个数量级",
        sub: "按官方牌价计算：简单客服任务在最便宜档位仅 $0.0004；旗舰模型跑多步智能体任务基准约 $2.5，高开销组合可到 $25。", source: "本报告测算 · 2026-07-17" },
    },

    // §4 渗透率警示仪表
    penetration: {
      value: "约 6%", numerator: "付费客户约 9,500（券商估）", denominator: "约 15 万客户基数",
      note: "$1.2B 年化收入与约 6% 的付费渗透率并存。",
      drill: { title: "Agentforce 付费渗透率", value: "约 6%（9,500 / 150,000）",
        sub: "券商估算口径；单独定价产品的付费渗透仍处个位数。", source: "券商研究 · 截至 2026-07-17" },
    },

    // §5 供需缺口三情景（读数旁固定印：区间 0.34–2.27 + 结论翻转开关 + "紧平衡 ≠ 短缺"）
    gap: {
      current: 0.7,
      cases: [
        { key: "tightening", name: "收紧", demand: 6.22, supply: 1.92, ratio12m: 2.27, color: "red",
          read: "需求高增长 + 供给低增长：缺口快速收紧" },
        { key: "base", name: "基准", demand: 3.94, supply: 2.85, ratio12m: 0.97, color: "blue",
          read: "需求仍快于供给，缺口逼近 1.0：稀缺加剧、强度温和" },
        { key: "loosening", name: "放松", demand: 2.15, supply: 4.4, ratio12m: 0.34, color: "ink",
          read: "需求失速 + 供给放量：稀缺缓解" },
      ],
      explainer: "缺口比 = 按需求和供给各自的增长速度折算出的比值——小于 1 表示供给还追得上（紧平衡），大于 1 表示越买越缺。缺口比小于 1 = 紧平衡，不等于短缺。",
      supplyNote: "供给端测算口径：行业估算全球加速器存量约 1,500–2,000 万颗 H100 当量（以 H100 算力为统一单位折算，方便比较不同年代、不同型号的芯片总量）；2026 年新增约 1,400–1,600 万颗（NVIDIA 约 750 万 + 自研芯片 700–900 万，摩根大通）；产能增速 1.9x × 服务速率增速 1.5x = 2.85x（基准情景）。服务速率按谷歌校准的 1,600 token/秒；行业标准性能测试峰值仅作上界。高带宽内存位元需求 +88%（UBS）；先进封装产能年增约 80–100%（台积电）。",
      flipSwitch: "结论翻转开关：中国模型租用服务一线基准增速 4.0x 若砍半到 2.0x，需求增速 3.94x→2.83x < 供给 2.85x，结论翻转为缺口缓解。承重假设 = 对结论贡献最大的那个假设——它一动，结论就动。",
      intensity: "强度乘数：推理模式单次请求约 10 倍 token；智能体多步循环单任务 15–1000 倍；推理输出长度年增约 5 倍。",
      thirdParty: "第三方对照：Exponential View 估全球 >30Q/月、同比 +14 倍；高盛估 2030 年 120Q/月。",
      drill: { title: "供需缺口比（本报告测算，base 情景）", value: "0.70→0.97（走廊 0.34–2.27）",
        sub: "不做点预测，只回答'需求与供给谁跑得更快'。读数为自建模型测算，无外部出处，故以区间呈现并附敏感性开关。", source: "本报告测算 · 2026-07-17" },
    },

    // §5 需求增长线（权重存精确值，页面显示 20/55/9/8/1/6，脚注"合计 99% 为显示舍入"；贡献份额口径 A）
    growthLines: {
      footnote: "权重显示合计 99% 为显示舍入；贡献份额 = 各线权重 × 增速占总加权增速的份额。",
      synth: { demand: 3.94, demandExact: 3.9386, total: 157.9, weightedSum: 621.9 },
      lines: [
        { id: "consumer", name: "消费聊天/搜索 AI", level: 32.0, weight: 0.2027, weightDisplay: "20%", low: 1.5, base: 2.0, high: 3.0, shareA: "10.3%",
          drill: { title: "消费聊天/搜索 AI", value: "增速基准 2.0x/年（悲观 1.5 / 乐观 3.0）；对基准增速贡献 10.3%",
            sub: "锚点：ChatGPT 消息 10 亿→25 亿/天（约 1.9x/年）、Gemini app 请求 +7x/年、AI Mode 查询量季度翻倍。用户扩张减速，但推理/多模态推高单次查询 token。", source: "官方披露 · 截至 2026-07-17" } },
        { id: "chinaModel", name: "中国模型租用服务", level: 87.6, weight: 0.5548, weightDisplay: "55%", low: 2.0, base: 4.0, high: 6.0, shareA: "56.3%",
          drill: { title: "中国模型租用服务（最大权重、承重假设）", value: "增速基准 4.0x/年（悲观 2.0 / 乐观 6.0）；对基准增速贡献 56.3%",
            sub: "锚点：豆包 12.7T→50T→120T→180T/天——同比 +10 倍（2026-06-23 火山引擎官方）；近 3 个月 +50%（年化约 5 倍），较 2025-12→2026-03 的 2.4 倍/季明显减速。百炼 3 个月 6 倍；非豆包约 60T/天（券商 2026-02）。口径是否含缓存/多模态未核验——结论的第一敏感假设。", source: "官方披露 · 2026-06-23" } },
        { id: "api", name: "全球 API/开发者", level: 14.3, weight: 0.0906, weightDisplay: "9%", low: 3.0, base: 5.0, high: 8.0, shareA: "11.5%",
          drill: { title: "全球 API/开发者", value: "增速基准 5.0x/年（悲观 3.0 / 乐观 8.0）；对基准增速贡献 11.5%",
            sub: "锚点：Google API 10B→16B→19B tokens/分钟（环比 +60%）、OpenRouter 5T→25T tokens/周（6 个月 5 倍）、OpenAI API 6B tokens/分钟（2025-10，两年 20 倍）。", source: "官方披露 · 截至 2026-07-17" } },
        { id: "coding", name: "编程智能体", level: 12.0, weight: 0.0760, weightDisplay: "8%", low: 4.0, base: 8.0, high: 15.0, shareA: "15.4%",
          drill: { title: "编程智能体（最快增长极）", value: "增速基准 8.0x/年（悲观 4.0 / 乐观 15.0）；对基准增速贡献 15.4%",
            sub: "锚点：Codex 周活 0.6M→5M+（5 个月 8 倍）→ 接近 1,000 万（匿名社交账号泄露，未独立核验）；单次模型升级周 token 量 5 倍 vs 用户 3 倍；Claude Code 9 个月 $0→年化 $2.5B。智能体单任务 token 为聊天的 15–1000 倍。", source: "官方披露 · 媒体报道与访谈 · 截至 2026-07-17" } },
        { id: "enterprise", name: "企业工作流智能体", level: 2.0, weight: 0.0127, weightDisplay: "1%", low: 3.0, base: 5.0, high: 8.0, shareA: "1.6%",
          drill: { title: "企业工作流智能体", value: "增速基准 5.0x/年；对基准增速贡献 1.6%",
            sub: "锚点：Salesforce 任务量单位 8 个季度 55 倍、累计 token 同比 5 倍。基数小，曲线最陡。", source: "官方披露 · 2026-05-27" } },
        { id: "residual", name: "无官方数据残差", level: 10.0, weight: 0.0633, weightDisplay: "6%", low: 2.0, base: 3.0, high: 5.0, shareA: "4.8%",
          drill: { title: "无官方数据残差", value: "增速基准 3.0x/年；对基准增速贡献 4.8%",
            sub: "Anthropic token 量、Meta AI、xAI 等无披露——'无官方数据'即只能靠模型估计的部分。旁证：Anthropic 年化收入 17 个月 47 倍。", source: "本报告测算 · 2026-07-17" } },
      ],
    },

    // §5 需求锚点对数轴多序列（Google/豆包/Anthropic/Codex 四线）
    anchors: [
      { id: "google", name: "Google 全平台 token 处理量", unit: "T/月",
        points: [ { date: "2024", value: 9.7 }, { date: "2025-05", value: 480 }, { date: "2025-10", value: 1300 }, { date: "2026-05", value: 3200 } ],
        note: "同比约 7 倍；近 7 个月年化约 4.7 倍——锚点在减速，引用须带减速限定。是否含缓存/多模态官方未披露。",
        drill: { title: "Google token 锚点", value: "9.7T/月（2024）→ 3.2Q/月（2026-05），同比约 7 倍",
          sub: "近 7 个月年化约 4.7 倍，锚点在减速。", source: "官方披露 · 2026-05" } },
      { id: "doubao", name: "豆包日调用量", unit: "T/天",
        points: [ { date: "2025-03", value: 12.7 }, { date: "2025-12", value: 50 }, { date: "2026-03", value: 120 }, { date: "2026-06", value: 180 } ],
        note: "同比 +10 倍（2026-06-23 火山引擎官方）；近 3 个月 +50%（年化约 5 倍），较 2025-12→2026-03 的 2.4 倍/季明显减速。",
        drill: { title: "豆包 token 锚点", value: "180T/天（2026-06），同比 +10 倍",
          sub: "近 3 个月 +50%（年化约 5 倍），明显减速；口径是否含缓存未核验。", source: "官方披露 · 2026-06-23" } },
      { id: "anthropic", name: "Anthropic 年化收入", unit: "$B",
        points: [ { date: "2024-12", value: 1 }, { date: "2026-02", value: 14 }, { date: "2026-04", value: 30 }, { date: "2026-05", value: 47 } ],
        note: "17 个月 47 倍。管理层年化收入口径，未经审计；与云厂商分成口径未拆。年化收入 = 按当前收入速度折算的一年收入。",
        drill: { title: "Anthropic 年化收入", value: "$1B（2024-12）→ $47B（2026-05），17 个月 47 倍",
          sub: "管理层口径，未经审计；与云厂商分成口径未拆。", source: "媒体报道与访谈 · 2026-05" } },
      { id: "codex", name: "Codex 周活跃用户", unit: "M",
        points: [ { date: "2026-01", value: 0.6 }, { date: "2026-06", value: 5 }, { date: "2026-07", value: 10 } ],
        note: "'接近 1,000 万'来自匿名社交账号泄露，未经独立核验；OpenAI API 6B tokens/分钟（2025-10，两年 20 倍）。",
        drill: { title: "Codex 周活锚点", value: "0.6M（2026-01）→ 5M+（2026-06）→ 接近 1,000 万",
          sub: "末点为泄露口径，未经独立核验。", source: "媒体报道与访谈 · 2026-07" } },
    ],

    // §6 四棒接力图（2022→2030，每棒：在位者/利润峰值/迁移触发事件；B 面并列）
    relay: [
      { rank: 1, name: "GPU", period: "2022 末–2023", incumbent: "NVIDIA",
        profitPeak: "毛利率 FY2023 56.9% → FY2024 72.7% → FY2025 75.0% → FY2026 约 71.1%（换代期回落）",
        trigger: "H100 终端售价 $25,000–30,000 vs 物料成本约 $3,320，加价约 7.5–9 倍；交期峰值约 52 周",
        drill: { title: "第一棒 · GPU（2022 末–2023）", value: "加价约 7.5–9 倍；数据中心收入 FY2023→FY2024 为 $15B→$47.5B（+217%）",
          sub: "超额利润随棒走：交期收敛后毛利率换代期回落。", source: "券商研究 · 2023-08" } },
      { rank: 2, name: "高带宽内存（HBM）", period: "2024–", incumbent: "SK hynix / Micron / 三星",
        profitPeak: "SK hynix 2025 营业利润 47.2 万亿韩元（利润率 49%，Q4 单季 58% 创纪录），年度营业利润首超三星",
        trigger: "2024 全部售罄、2025'几乎售罄'（CEO 2024-05-02）；2023 营业亏损 7.7 万亿 → 2025 营收 97.15 万亿（+46.8%）；2026-07-10 纳斯达克 IPO 募资 265 亿美元、7 倍超购",
        drill: { title: "第二棒 · 高带宽内存（2024–）", value: "Micron 2026 年 HBM 售罄、2027 年 HBM4 全订完（2026-06-24）",
          sub: "价格二次冲高：HBM4 2027 年合约价或数倍上涨；SK hynix 以 5 年以上长约锁定 60–70% 量价。HSBC 估 2026 年 HBM 供给缺口约 8%（该机构另有 6%→9% 的口径，两数并列待核）。Gartner：2026 年内存成本 +130%。B 面：2026 年一季度起 HBM 每片晶圆收入已被普通服务器内存条（DDR5 RDIMM）反超。",
          source: "官方披露 · 行业机构 · 2026-07-10" } },
      { rank: 3, name: "先进封装（CoWoS）", period: "2023–", incumbent: "台积电",
        profitPeak: "台积电 2026 Q1 毛利率 66.2%；资本开支上调至 $60–64B",
        trigger: "月产能 2022 约 1 万片 → 2023 底 11,000 → 2024 底 35,000–40,000 → 2025 底 65,000–80,000 → 2026 约 70,000–93,000 → 2027 向 12–13 万片/月爬坡（各口径分歧大）；2026 需求约 100 万片/年，NVIDIA 占约 60%",
        drill: { title: "第三棒 · 先进封装（2023–）", value: "'severely supply-constrained'（严重供不应求）——2026-07-16 法说会",
          sub: "魏哲家：后段封装已成为限制客户成长的瓶颈。绕行方案（早期）：Intel EMIB 由 Amkor 在韩国/葡萄牙/亚利桑那高量产（2025-12）；拿不到产能的客户转向日月光/矽品等替代封装（2026-07-13）。",
          source: "官方披露 · 2026-07-16" } },
      { rank: 4, name: "电力", period: "2025 下半年–", incumbent: "电力设备与交付链",
        profitPeak: "见 §7：燃机在手订单 100GW、PJM 拍卖连续四次触顶",
        trigger: "标志事件：纳德拉 2025-11 中旬公开承认'芯片躺在库存里插不上电'（BG2 播客）",
        drill: { title: "第四棒 · 电力（2025 下半年–）", value: "唯一资本无法速成的约束",
          sub: "电力设备链当前的位置类似 2023 年的先进封装。", source: "官方披露 · 2025-11" } },
    ],

    // §6 瓶颈硬度交期对数横条 + 晶圆损耗注
    hardness: {
      bars: [
        { item: "GPU", display: "6–12 周", weeksMin: 6, weeksMax: 12, note: "芯片瓶颈 24 个月内从 52 周收敛到 6–16 周" },
        { item: "高带宽内存排产", display: "36–52 周", weeksMin: 36, weeksMax: 52, note: "长约锁量 60–70%" },
        { item: "大型变压器", display: "128 周", weeksMin: 104, weeksMax: 210, note: "升压变 144 周、最大机型 210 周" },
        { item: "大型燃机", display: "约 5 年", weeksMin: 260, weeksMax: 260, note: "现下单 2028 年交付" },
        { item: "负荷侧并网", display: "4–7 年", weeksMin: 208, weeksMax: 364, note: "北弗吉尼亚/凤凰城/达拉斯热点枢纽" },
        { item: "PJM 大负荷接网端到端", display: "超 8 年", weeksMin: 416, weeksMax: 416, note: "2026-06 口径" },
      ],
      waferNote: "晶圆损耗（两个口径并列）：每 GB HBM 的晶圆消耗约为 DDR5 的 3 倍；1GB HBM 的晶圆面积当量约等于 4GB 普通 DRAM。2026 年 AI 占全球 DRAM 晶圆产能约 20%。",
      bside: "B 面：TrendForce（2026-06-02）——2026 年一季度起，HBM 每片晶圆的收入已被普通服务器内存条反超，HBM 利润率已低于高端服务器 DRAM。",
    },

    // §6 单卡内存容量阶梯链（单卡内存容量上限持续抬升，驱动瓶颈单向迁移）
    hbmLadder: [
      { gen: "H100", capacity: "80GB", bandwidth: "", year: "2022", note: "" },
      { gen: "H200", capacity: "141GB", bandwidth: "", year: "2024", note: "" },
      { gen: "B200", capacity: "192GB", bandwidth: "8 TB/s", year: "2025", note: "" },
      { gen: "Rubin", capacity: "288GB HBM4", bandwidth: "22 TB/s", year: "2026", note: "HBM4 标准（JEDEC 2025-04）：位宽 1024→2048 bit、单栈带宽 ≥2 TB/s；Micron HBM4 >2.8 TB/s = HBM3E 的 2.3 倍、能效 +20%" },
      { gen: "Rubin Ultra", capacity: "1TB HBM4e", bandwidth: "4.6 PB/s", year: "2027 下半年", note: "单柜 600 kW" },
    ],

    // §7 美国电力瓶颈地图（点标 + 区域标记，支持缩放）
    powerMap: {
      explainer: "通电速度（speed-to-power）= 从申请并网到实际用上电的时间。",
      nodes: [
        { id: "nva", name: "北弗吉尼亚", type: "hub", value: "负荷侧接网 4–7 年",
          drill: { title: "热点枢纽接网", value: "北弗吉尼亚、凤凰城、达拉斯 4–7 年",
            sub: "美国已承诺大负荷接网申请约 160GW（Wood Mackenzie）。", source: "行业机构 · 截至 2026-07-17" } },
        { id: "phx", name: "凤凰城", type: "hub", value: "负荷侧接网 4–7 年", drill: { title: "凤凰城", value: "负荷侧接网 4–7 年", sub: "", source: "行业机构 · 截至 2026-07-17" } },
        { id: "dal", name: "达拉斯", type: "hub", value: "负荷侧接网 4–7 年", drill: { title: "达拉斯", value: "负荷侧接网 4–7 年", sub: "", source: "行业机构 · 截至 2026-07-17" } },
        { id: "pjm", name: "PJM 区域（美国最大电网运营商）", type: "region", value: "2028/29 年度缺口 6,831MW",
          drill: { title: "PJM 容量市场", value: "连续第四次触顶；备用率 14.4% vs 20% 目标",
            sub: "2028/29 年度（2026-07-14 公布）：缺口扩至 6,831MW；联邦能源监管委员会批准上限下调 2.5% 至 $325。", source: "官方披露 · 2026-07-14" } },
        { id: "abilene", name: "得州 Abilene（Stargate）", type: "project", value: "约 600MW 在运，2026 年中目标 1.2GW",
          drill: { title: "Stargate Abilene", value: "29 台 × 34MW 燃机（装机合计约 986MW），约 600MW 已在运行",
            sub: "2026 年中目标 1.2GW。", source: "行业机构 · 截至 2026-07-17" } },
        { id: "memphis", name: "田纳西孟菲斯（xAI）", type: "project", value: "约 495MW 在运",
          drill: { title: "xAI Colossus（孟菲斯）", value: "Colossus 1 以 122 天建成投产；孟菲斯区域合计约 495MW 在运",
            sub: "场地电网仅 8MW，先装 14 台燃机约 35MW，2025-04 达 35 台燃机约 421–422MW（早期批次单机功率较小、后期批次较大）；495MW 与 421–422MW 为不同时点口径。", source: "行业机构 · 截至 2026-07-17" } },
        { id: "tmichrane", name: "宾州三里岛（Crane）", type: "nuclear", value: "835MW · 20 年长期购电协议",
          drill: { title: "Microsoft–Constellation 三里岛重启", value: "835MW、20 年协议、重启成本 $1.6B、能源部 $1B 贷款",
            sub: "目标 2027 下半年投运；2026-06-04 联邦能源监管委员会批准豁免转移 760MW。长期购电协议（PPA）= 锁定多年电量与价格的合同。", source: "官方披露 · 2026-06-04" } },
        { id: "michigan", name: "密歇根", type: "moratorium", value: "$1B 项目撤回案例",
          drill: { title: "社区反对与撤回", value: "$1B 数据中心项目撤回；至少 10 州出现暂停令标记",
            sub: "选址监管套利的另一面：社区与监管阻力在上升。", source: "媒体报道与访谈 · 截至 2026-07-17" } },
      ],
      stats: [
        { label: "并网排队容量（2024 底）", value: "约 2,290GW（1,400GW 发电 + 890GW 储能，约 10,300 个项目）" },
        { label: "并网排队容量（2025 底）", value: "2,061GW（−10%，部分因监管改革清退投机申请）" },
        { label: "建成项目中位等待", value: "5 年（2000–2007 年不足 2 年）；2000–2019 年入队容量仅约 13% 建成、约 77% 撤回" },
        { label: "2026 年计划项目延期", value: "预计 30–50%（2025 年 110 个计划项目 26% 延期）" },
        { label: "自备电源", value: "全美至少 46 个站点规划合计 56GW（约占规划中容量 30%）；已明确设备的 23GW 中约 75% 为天然气" },
        { label: "数据中心用电（IEA）", value: "2024 约 415 TWh → 2030 约 945 TWh（超日本全国）；北美机房空置率 1.4% 历史最低" },
      ],
      bside: "B 面三条：GE Vernova CEO（2026-04-22）自称燃机'并非真正的卡点和瓶颈'（瓶颈在工程总包/许可/燃料）；摩根士丹利（2026-03）测算 2028 年电力净缺口基准情形基本收敛；并网排队 2025 年底回落约 10%。",
    },

    // §7 PJM 拍卖价格轨迹（分段标注 +833% / 累计 +1,053%，不可混标）
    pjm: {
      points: [
        { auction: "2024/25", price: 28.92, note: "" },
        { auction: "2025/26", price: 269.92, note: "自 $28.92 起 +833%" },
        { auction: "2027/28", price: 333.44, note: "连续第三次触顶；史上首次未满足备用要求；缺口 6,625MW（以 PJM 官方 PDF 为准；RTO Insider 记 6,516MW 并存）；无价格帽模拟价 $529.80" },
        { auction: "2028/29", price: null, note: "缺口 6,831MW；备用率 14.4% vs 20% 目标；连续第四次触顶；联邦能源监管委员会批准上限下调 2.5% 至 $325（2026-07-14 公布）" },
      ],
      segments: [
        { from: 28.92, to: 269.92, label: "+833%（2024/25→2025/26）" },
        { from: 28.92, to: 333.44, label: "累计 +1,053%（2024/25→2027/28）" },
      ],
      unit: "$/MW-day",
      drill: { title: "PJM 容量拍卖轨迹", value: "$28.92→$269.92 = +833%；全程 $28.92→$333.44 累计 +1,053%",
        sub: "两个数字端点不同、不可混标。触顶区间 $325–333；无帽模拟 $529.80。", source: "官方披露 · 2026-07-14" },
    },

    // §7 电力硬度三柱
    powerHard: [
      { label: "并网排队（建成项目中位）", value: "5 年", note: "2000–2007 年不足 2 年；约 77% 入队项目撤回", source: "行业机构 · 2025" },
      { label: "大型变压器交期", value: "36–48 个月", note: "大型 24–36 个月、升压/超高压 36–48 个月、最大机型 210 周；公用事业以 15% 不可退定金提前 3–4 年锁产线；瓶颈材料取向硅钢全球年产能仅约 250–300 万吨", source: "行业机构 · 2026-05-11" },
      { label: "大型燃机交付", value: "2028 年", note: "新订单交期约 5 年；气轮机价格 2027 年底约 $600/kW，较 2019 年 +195%；GE Vernova 燃机在手订单 80GW（2025 底）→ 100GW（2026 Q1：44GW 确定 + 56GW 预订），正谈 2030 年槽位；上调 2028 年指引至营收 $52B、核心经营利润率 20%", source: "官方披露 · 行业机构 · 2026-05" },
    ],

    // §8 融资结构瀑布（本章核心图）
    financeFall: {
      stages: [
        { id: "ocf", label: "经营现金流", amount: null, note: "基本盘：2026 年四家资本开支指引合计约相当于经营现金流的 90–100%（UBS 约 100%、公开测算 92%，口径敏感；过去 10 年均值约 40%）" },
        { id: "bond", label: "发债", amount: 159, note: "2026 年迄今五大云厂商发债 $159B（Dealogic，截至 2026-06 初，同比 +47%；2025 全年 $108B、2024 仅 $17B）；2026 年全球 AI 相关债券融资约 $335B（含项目债与新兴算力租赁商，超 2025 全年 2 倍）；UBS 看超大云厂商全年 $230–240B（预测口径）；2026-07-10 长端 AI 债遭抛售" },
        { id: "offbs", label: "表外租赁/合资", amount: null, parts: [
          { name: "Microsoft 未开始租赁", amount: 155.1, note: "$92.7B→$155.1B（半年 +67%）；Microsoft 是唯一未发债的超大云厂商" },
          { name: "Meta Hyperion 表外合资", amount: 27, note: "Blue Owl 占 80%；四位参议员致函美国金融稳定监督委员会" },
          { name: "Amazon 表外未开始租赁 + 采购义务", amount: 181.2, note: "$96.4B + $84.8B；2025 以来投资级发债 >$82B" },
        ] },
        { id: "vendor", label: "供应商资金循环", amount: null, parts: [
          { name: "NVIDIA 对 CoreWeave 未售容量购买义务", amount: 6.3, note: "公司申报文件" },
          { name: "NVIDIA 对 OpenAI 意向书作废 → 股权", amount: 30, note: "$100B 意向书于 2026-02 作废（FT 报道），转为 $30B 股权；黄仁勋 2026-03-04 称对该公司的投资'很可能是最后一笔'" },
          { name: "AMD–OpenAI", amount: null, note: "6GW + 1.6 亿股认股权证" },
        ], note: "NewStreet 估算：NVIDIA 约 $10B 对外投资对应约 $35B GPU 收入。供应商给客户掏钱买自己产品的循环，先于需求解体。" },
      ],
      drill: { title: "从花自己赚的钱转向借钱扩张", value: "2026 年迄今五大云厂商发债 $159B（同比 +47%）",
        sub: "杠杆：超大云厂商净债务/核心经营利润两个季度从 0.9 倍 → 1.8 倍（摩根士丹利 2026-07-08 测算，单一来源、公开不可核）；高盛当周建议客户对冲超大云厂商债务泡沫。", source: "行业机构 · 券商研究 · 2026-07-08" },
    },

    // §8 资本开支分组柱（公司披露现金口径）+ 阈值图
    capex: {
      basis: "公司披露现金口径（FY2025 四家合计 $359.9B，+64%）；禁止与券商汇总口径跨口径拼列",
      companies: [
        { name: "Microsoft", fy2023: 28.1, fy2024: 44.5, fy2025: 64.6, ttm: 97.2, guide2026: "约 190", q1Ratio: 0.66, commitRatio: 1.05, capexOcf: "约 65%",
          note: "6 月财年、现金口径（含融资租赁 FY25 = 88.2）；唯一未发债的超大云厂商，但未开始租赁半年 +67% 至 $155.1B" },
        { name: "Alphabet", fy2023: 32.3, fy2024: 52.5, fy2025: 91.4, ttm: 109.9, guide2026: "180–190", q1Ratio: 0.78, commitRatio: 1.81, capexOcf: "55%",
          note: "现金 PPE；无股权融资——实为发债 $25B+$32B（含 £1B 100 年期债、票息 6.125%）；Google Cloud 在手订单 $462B" },
        { name: "Amazon", fy2023: 52.7, fy2024: 83.0, fy2025: 131.8, ttm: 151.0, guide2026: "约 200", q1Ratio: 1.70, commitRatio: 5.47, capexOcf: "94%",
          note: "现金 PPE（$131.8B/$139.5B = 资本开支/经营现金流 94%）；更硬口径：自由现金流 $38.2B→$11.2B；2026 Q1 当季买设备花的现金（$44.2B）第一次超过了生意赚回的现金——现金压力最高（红灯）" },
        { name: "Meta", fy2023: 28.1, fy2024: 39.2, fy2025: 72.1, ttm: 78.2, guide2026: "125–145", q1Ratio: 0.59, commitRatio: 1.84, capexOcf: "62%",
          note: "公司定义口径 = PP&E + 融资租赁本金；发债 $30B（认购 $125B）+ 约 $25B（认购缩至约 $96B，−23%——但对发行额仍是 3.8 倍覆盖，'疲态'是相对读数）" },
      ],
      totals: { fy2023: 141.2, fy2024: 219.2, fy2024yoy: "+55%", fy2025: 359.9, fy2025yoy: "+64%", ttm: 436.3,
        guide2026: "695–725", guide2026yoy: "+93%~+101%（中值约翻倍）", capexOcfFy2025: 0.65, capexOcfTtm: 0.71 },
      altBasis: { name: "券商汇总口径（含融资租赁）", total2025: 412.9, yoy: "+68%",
        note: "与公司披露现金口径差额约 $53B，几乎全部为 Microsoft 口径差（券商口径按日历年 $118.0B）；仅作备选并强制口径注，不作独立证据。" },
      threshold: { line: 1.0, label: "当季购设备现金/经营现金流 = 1.0 语义红线",
        note: "2026 Q1：Microsoft 0.66×、Alphabet 0.78×、Amazon 1.70×（红灯）、Meta 0.59×；已签约付款承诺/年化经营现金流：1.05×/1.81×/5.47×/1.84×（本报告测算，基于官方季报）" },
      recovery: { title: "回收质量（本报告测算）",
        aiProxy: "当年 AI 经营利润近似指标 / AI 相关资本开支：Microsoft 0.11×、Alphabet 0.10×、Amazon 0.17×、Meta 0.10×——四家均未闭合",
        cover: "年度资本费用覆盖：Amazon 0.81× 最接近，其余 0.46–0.52×" },
      weakNodes: [
        { name: "Oracle", facts: "已签约未交付合同 $553B（+325%）；以下三项均为媒体报道、未独立核验：Barclays 测算现金撑到 2026-11、5 年债务违约保险价 >125bp（2009 以来最高）、$14B 项目债据传被拒购", source: "官方披露 · 媒体报道与访谈 · 截至 2026-07-17" },
        { name: "CoreWeave（新兴算力租赁商）", facts: "债务 $24.9B；利息占收入 25.8%（2026 Q1 单季口径：利息 $536M / 收入 $2.08B，全年利息将随新债上升）；调整后核心经营利润率 46.3%；Fitch 评级 BB+（2026-05-18 上调）；2026 资金缺口约 $17B；在手订单 $99.4B = 47.8 倍季度收入", source: "官方披露 · 券商研究 · 2026-05-18" },
      ],
      bullCards: "多头硬牌（须并列）：H100 一年期租金反弹 40% 至 $2.35/GPU·小时（SemiAnalysis 2026-04-06）；AWS Q1 +28% 为十五个季度最快；Google Cloud 在手订单 $462B；Cerebras 已签约未交付合同 $24.6B = 48.2 倍 2025 年收入（上市申请文件坐实）。",
      k3Sidebar: "有市场观点将 2026 年 7 月 16–17 日板块调整归因于新模型发布。我们核查了主要公开分析，未发现支持该归因的证据，故本报告不采纳这一解释。主流归因是台积电上调资本开支引发现金流担忧、存储股获利了结与杠杆 ETF 踩踏。更深一层的判断是：新模型证明了单位智能成本可以大幅下降，但压缩成本释放的是更多需求——这不构成'资本开支无用'的证据。",
    },

    // §8 ≥100% 先例矩阵（资本开支超经营现金流且无保底回报的历史样本）
    precedentMatrix: {
      verdict: "资本开支超过经营现金流且无保底回报的历史样本里，没有活下来的先例。",
      cases: [
        { name: "电信（1996–2001）", outcome: "崩", note: "融资超 $2 万亿；需求神话'流量 100 天翻番'（实际为一年翻番）；供应商融资敞口 2000 年底约 $25.6B；资本退潮 → 设备商加速放贷续命 → 48 家地方性电信商同步破产。同构点 = 同步性风险：同一融资源头退潮时所有弱节点同时失血。" },
        { name: "页岩油", outcome: "崩", note: "资本开支长期超现金流，价格反转后全行业减记。" },
        { name: "Intel", outcome: "受挫", note: "重资产扩产遭遇需求与制程双重错配。" },
        { name: "公用事业", outcome: "没崩", note: "唯一例外——监管保底回报。" },
        { name: "Amazon 2010–14", outcome: "误引", note: "常被引为反例，但当时资本开支并未持续超过经营现金流，是误引。" },
      ],
      source: "行业机构 · 史料",
    },

    // §8 OpenAI 承诺构成条（对照年化收入约 $25B 参考线）
    openaiCommit: {
      total: "8 年约 $1.4 万亿", durationYears: 8,
      parts: [
        { name: "Oracle", amount: 300, note: "约 $300B" },
        { name: "Microsoft", amount: 250, note: "$250B" },
        { name: "AWS", amount: 38, note: "$38B" },
        { name: "CoreWeave", amount: 22.4, note: "约 $22.4B" },
      ],
      partsNote: "主要构成，未穷尽；产能承诺不等于现金资本开支，不入硬承诺分母。",
      compare: { arr: "年化收入约 $25B（2026-02）", burn: "2024–2029 累计烧钱预计 >$140B" },
      drill: { title: "OpenAI 承诺构成", value: "8 年约 $1.4 万亿 vs 年化收入约 $25B",
        sub: "承诺约为当前年化收入的 56 倍量级；2024–2029 累计烧钱预计 >$140B。", source: "官方披露 · 媒体报道与访谈 · 券商研究 · 截至 2026-07-17" },
    },

    // §9 利润池瀑布/100% 堆叠条（六层 × 三情景；模型层水下红；分母口径图注必写）
    profitPool: {
      scenarios: ["悲观", "基准", "乐观"],
      pools: { positive: { low: 73.79, base: 91.69, high: 121.14 }, net: { low: 61.79, base: 86.69, high: 121.14 } },
      denominatorNote: "正利润池 = 情景内正值层之和（悲观/基准不含模型层，乐观含 +$4B）；模型层单列净利润池份额并注明分母：悲观 −19.4%（−$12.00B/$61.79B）、基准 −5.8%（−$5.00B/$86.69B）、乐观 +3.3%（+$4.00B/$121.14B）。",
      layers: [
        { id: "semiconductor", name: "半导体（GPU/高带宽内存/先进封装/设备）", low: 59.33, base: 65.33, high: 73.33,
          share: { low: "80.4%", base: "71.3%", high: "60.5%" },
          drill: { title: "半导体层", value: "基准 $65.33B/季（走廊：悲观 $59.33B / 乐观 $73.33B）",
            sub: "NVIDIA $49.33B + 其他 $16B（Broadcom AI $10.8B/季、+143%，全财年目标 $56B；高带宽内存/先进封装/设备估算）。AI 业务单独利润率未披露是最大敏感项。", source: "官方披露 · 本报告测算 · 2026-07-17" } },
        { id: "cloud", name: "云/AI 算力", low: 7.96, base: 10.36, high: 13.81,
          share: { low: "10.8%", base: "11.3%", high: "11.4%" },
          drill: { title: "云/AI 算力层", value: "基准 $10.36B/季（走廊：悲观 $7.96B / 乐观 $13.81B）",
            sub: "Microsoft AI + AWS 自研芯片 + Google Cloud AI 份额（15/30/50% 区间）+ AWS AI 服务；AI 份额未披露。", source: "管理层口径 · 本报告测算 · 2026-07-17" } },
        { id: "dcpower", name: "数据中心/电力/液冷", low: 4.0, base: 8.0, high: 13.0,
          share: { low: "5.4%", base: "8.7%", high: "10.7%" },
          drill: { title: "数据中心/电力/液冷层", value: "基准 $8B/季（走廊：悲观 $4B / 乐观 $13B）",
            sub: "GE Vernova 在手订单 $163B、伊顿数据中心在手订单约 12 年建设量、Vertiv +80.8%、CoreWeave $99.4B。", source: "官方披露 · 券商研究 · 2026-07-17" } },
        { id: "workflow", name: "工作流软件", low: 2.0, base: 6.0, high: 12.0,
          share: { low: "2.7%", base: "6.5%", high: "9.9%" },
          drill: { title: "工作流软件层", value: "基准 $6B/季（走廊：悲观 $2B / 乐观 $12B）",
            sub: "Agentforce 年化 $1.2B（+205%）、ServiceNow 目标上调至 $1.5B、Adobe >$500M、Copilot 席位 2,000 万+；渗透率警示约 6%。", source: "官方披露 · 本报告测算 · 2026-07-17" } },
        { id: "services", name: "服务/集成", low: 0.5, base: 2.0, high: 5.0,
          share: { low: "0.7%", base: "2.2%", high: "4.1%" },
          drill: { title: "服务/集成层", value: "基准 $2B/季（走廊：悲观 $0.5B / 乐观 $5B）",
            sub: "企业落地服务的收入 × 利润率情景；规模和可持续性弱于软件与上游。", source: "本报告测算 · 2026-07-17" } },
        { id: "modellab", name: "模型/接口层（净利润口径）", low: -12.0, base: -5.0, high: 4.0,
          share: { low: "-19.4%", base: "-5.8%", high: "3.3%" },
          drill: { title: "模型/接口层净利润", value: "基准 −$5B/季，按净利润池口径 −5.8%（走廊：悲观 −19.4% / 乐观 +3.3%）",
            sub: "OpenAI 2025 年经营亏损 −$20.92B（平均约 −$5.2B/季，审计报道口径）；Anthropic 年化收入 $47B（管理层口径，未经审计）；其 2026 Q2 经营利润转正说法（+$0.559B、利润率 5.1%）为二手转述，口径有争议，未独立核验。", source: "媒体报道与访谈 · 本报告测算 · 2026-07-17" } },
      ],
      hardwareSubpool: [
        { name: "NVIDIA/GPU 系统", share: "约 70.1%" },
        { name: "其他半导体（高带宽内存/先进封装/设备）", share: "约 19.9%" },
        { name: "数据中心电力/液冷/交付", share: "约 10.0%" },
      ],
      hardwareNote: "服务器代工与普通 PCB 不是主要利润池。",
      officialAnchors: "NVIDIA FY2027 Q1（截至 2026-04-26）数据中心收入 $75.2B/季（+92%）、全公司收入 $81.615B、经营利润 $53.536B、毛利率 74.9%；Google Cloud Q1 收入 $20.028B / 经营利润 $6.598B / 在手订单 >$460B；Broadcom FY2026 Q2 AI 半导体 $10.8B（+143%）、全财年目标 $56B。",
      readout: "基准情景正利润池 $91.69B/季：半导体 71.3%、云 11.3%、数据中心/电力 8.7%、工作流软件 6.5%、服务 2.2%、模型层 0%（净利润口径 −5.8%）。半导体份额较上一期测算微降，是数据中心/电力与应用层锚点增强带来的相对稀释，并非上游走弱。哑铃结构：上游稀缺环节与下游工作流软件都能赚钱，中间的通用包装层最容易被挤压。",
    },

    // §9 算力开支传导桑基图（结构示意，不按金额精确比例）
    sankey: {
      note: "流向为模型公司算力开支的去向结构示意：模型公司的成本，是云/半导体/数据中心各层的收入。",
      nodes: [ "OpenAI", "Anthropic", "Microsoft Azure", "Google Cloud", "AWS", "Oracle", "NVIDIA", "Broadcom", "数据中心/电力" ],
      flows: [
        { from: "Anthropic", to: "Google Cloud", label: "云与 TPU" },
        { from: "Anthropic", to: "AWS", label: "云" },
        { from: "Anthropic", to: "Broadcom", label: "定制芯片" },
        { from: "OpenAI", to: "Microsoft Azure", label: "云" },
        { from: "OpenAI", to: "Oracle", label: "云基建（约 $300B 承诺）" },
        { from: "OpenAI", to: "NVIDIA", label: "GPU" },
        { from: "Microsoft Azure", to: "NVIDIA", label: "GPU 采购" },
        { from: "Google Cloud", to: "数据中心/电力", label: "自建与交付" },
      ],
    },

    // §9 订单覆盖倍数排行横条（需求硬度证据）
    coverage: [
      { name: "CoreWeave", ratio: 47.8, display: "47.8×", base: "在手订单 $99.4B / 季度收入 $2.078B", source: "官方披露 · 截至 2026-07-17" },
      { name: "Cerebras", ratio: 48.2, display: "48.2×", base: "已签约未交付合同 $24.6B / 2025 收入 $0.510B（上市申请文件坐实）", source: "官方披露 · 截至 2026-07-17" },
      { name: "伊顿（Eaton）", ratio: null, display: "约 12 年", base: "数据中心在手订单约等于 2025 年建设速度的 12 年；订单同比 +240%；电气收入占比 73.3%", source: "官方披露 · 截至 2026-07-17" },
      { name: "nVent", ratio: 2.09, display: "2.09×", base: "在手订单 / 季度销售", source: "官方披露 · 截至 2026-07-17" },
      { name: "GE Vernova", ratio: null, display: "$163B", base: "在手订单 $163B；数据中心订单占比 13.1%", source: "官方披露 · 截至 2026-07-17" },
      { name: "Nebius", ratio: null, display: "+683.9%", base: "收入同比 +683.9%", source: "官方披露 · 截至 2026-07-17" },
    ],

    // §9 六种"租"产业链地图（分层架构图，玩家落位）
    rents: [
      { id: "scarcity", name: "稀缺租", players: "NVIDIA / 台积电 / 高带宽内存三家 / 先进封装 / 电力设备",
        meaning: "因为东西稀缺而多赚到的超额利润——不是因为做得更好，而是因为别人拿不到。", risk: "租金随棒移交均值回归；合同价转跌 + 交期缩短即终结。" },
      { id: "scheduling", name: "调度租", players: "AWS / Azure / GCP / CoreWeave",
        meaning: "把稀缺算力排队分配收到的租。", risk: "资本开支与折旧压力；利用率与租金价格双下行即恶化。" },
      { id: "intelligence", name: "智能租", players: "OpenAI / Anthropic / Google DeepMind",
        meaning: "模型能力本身的溢价。", risk: "尚未证明留存利润；前沿档溢价能否扛住编程智能体放量。" },
      { id: "integration", name: "集成租", players: "数据与治理平台",
        meaning: "把 AI 装进企业现有数据与权限体系的租。", risk: "被平台厂商垂直整合。" },
      { id: "agenttools", name: "智能体工具租", players: "路由 / 观测 / 评测工具",
        meaning: "智能体工作流的卖水人。", risk: "单功能壳层最易被挤压。" },
      { id: "workflow", name: "工作流租", players: "Microsoft / Salesforce / ServiceNow / Adobe",
        meaning: "记录系统级工作流 + 明确付费单位的租。", risk: "付费渗透个位数；续费质量待验证。" },
      { id: "servicefee", name: "转型服务费", players: "咨询与集成商",
        meaning: "企业落地的一次性服务费。", risk: "可持续性弱于产品与上游。" },
    ],

    // §10 中国产业链 11 层分层图（证据强/观察/证据弱三色，点击下钻公司数字与口径）
    chinaLayers: {
      classNote: "证据强 = 有可验证的股东利润锚点；观察 = 逻辑成立、缺直接披露；证据弱 = 使用量大但利润未证明。月活、token、下载量一律不能当利润证据，必须过'付费率 → 每用户平均收入 → 推理成本 → 毛利 → 补贴剥离'利润桥。",
      layers: [
        { id: "modelapp", name: "模型/应用", cls: "证据弱", companies: [
          { name: "豆包", facts: "月活 3.45 亿、180 万亿 token/天", note: "使用暴涨 ≠ 股东利润" },
          { name: "腾讯", facts: "AI 新品拖累单季经营利润约 88 亿元", note: "剔除 AI 新品 844 亿 +17% vs 含 AI 756 亿 +9%" },
          { name: "金山办公", facts: "WPS AI 月活 8,013 万（+307%）", note: "无 AI 单独收入" },
        ] },
        { id: "cloud", name: "云/AI 算力", cls: "证据强", companies: [
          { name: "阿里云", facts: "AI 产品收入 89.71 亿元/季（占云外部收入 30%，连续 11 季三位数）；AI 年化收入 >358 亿元，其中模型租用服务（百炼）年化 >80 亿元", note: "唯一可验证的模型经济收入层" },
          { name: "百度智能云", facts: "2026 Q1 AI 云基建收入 8.8 亿元（+79%）", note: "" },
        ] },
        { id: "chip", name: "国产芯片", cls: "证据强", companies: [
          { name: "寒武纪", facts: "2025 收入 64.97 亿元（+453.21%）、净利 20.59 亿元、净利率 31.7%", note: "只能表述为'AI 资本开支/国产替代供给链利润'，严禁写成'前沿模型利润'" },
          { name: "海光", facts: "2025 收入 143.77 亿元、净利 25.45 亿元、净利率 17.7%；2026 上半年预告净利 +41.5%~52.3%（07-16）", note: "国产替代利润已验证" },
          { name: "摩尔线程", facts: "上半年预告营收 +135%~149%，Q1 扭亏", note: "" },
        ], note: "'字节洽购芯片'类传闻属媒体报道与访谈，不进已验证层。" },
        { id: "manufacturing", name: "制造", cls: "观察", companies: [], note: "先进制程代工扩产承接国产替代订单；直接披露有限，详见出口管制章情景矩阵。" },
        { id: "memory", name: "存储", cls: "证据强", companies: [
          { name: "长鑫科技", facts: "2025 收入 618.0 亿元、净利 330.1 亿元；7-16 申购、截至 2026-07 为科创板募资规模最大的 IPO、7-27 上市", note: "招股书指引 2026 上半年净利大幅超上年全年同期（具体数字以招股书为准）；HBM 仍处 16nm HBM3 样品阶段——定性为周期红利（跟着行业周期涨跌的钱，区别于稀缺带来的超额利润），非 HBM 稀缺利润" },
        ] },
        { id: "equipment", name: "设备", cls: "观察", companies: [], note: "国产设备订单在收紧情景下加速；当前按国产替代资本开支利润延续观察。" },
        { id: "materials", name: "材料", cls: "观察", companies: [], note: "同设备层。" },
        { id: "packaging", name: "先进封装", cls: "观察", companies: [], note: "国产先进封装产能跟随国产芯片放量；缺直接利润披露。" },
        { id: "pcb", name: "高端 PCB", cls: "证据强", companies: [
          { name: "沪电股份", facts: "AI 相关 PCB 占总收入 59.0%、占数据通信 PCB 76.2%、PCB 毛利率 36.91%", note: "中国硬件链里最干净的 AI 基础设施收入暴露" },
          { name: "胜宏科技", facts: "净利率 22.4%", note: "" },
        ] },
        { id: "optical", name: "光模块", cls: "证据强", companies: [
          { name: "中际旭创", facts: "2025 收入 382.4 亿元、净利 108.0 亿元、光模块毛利率 42.6%；2026-07-12 首次官方承认'部分原有客户需求下调'，新云厂商/AI 客户上调对冲，订单覆盖 2026 全年排至 2027", note: "读法从'需求单边上修'改为'结构轮动、总量仍紧'" },
          { name: "新易盛", facts: "毛利率 47.8%；卖方预期 2026 净利约 185 亿元（+94%）", note: "卖方预测与已实现订单分层标注" },
          { name: "源杰", facts: "Q1 净利 +1153%", note: "" },
        ] },
        { id: "aidc", name: "AI 数据中心/电力", cls: "证据强", companies: [
          { name: "润泽科技", facts: "AI 数据中心收入 25.10 亿元（占 44.24%）、该业务毛利率 48.50%、成熟资产上架率 >90%、累计交付 750MW", note: "唯一有直接利润锚点的公司；须用扣非口径（扣除一次性收益后的净利润）：归母 50.50 亿 vs 扣非 19.01 亿，归母含不动产信托基金（REITs）投资收益" },
          { name: "奥飞数据", facts: "财务费用/收入 12.17%", note: "转型中" },
          { name: "数据港", facts: "401MW 在运，但智算收入占比仅 0.21%", note: "未来期权：目前贡献很小" },
        ] },
      ],
      counterExamples: [
        { name: "浪潮信息", facts: "收入 1,647.82 亿元，但服务器毛利率 4.52%、净利率 1.46%、库存/收入 28.2%", note: "放量 ≠ 稀缺利润" },
        { name: "华勤", facts: "净利率 2.36%", note: "只赚过手钱（收入高、利润薄）" },
      ],
      huaweiNote: { claim: "华为韬（τ）定律：逻辑折叠在固定节点实现 55% 晶体管密度提升、41% 能效增益；381 款芯片、2031 年等效 1.4nm",
        tier: "公司声称/预印本，未经第三方验证", note: "只放观察名单。证据可信度三层：官方发布 / 预印本 / 媒体转述。" },
    },

    // §10 AI 数据中心利润桥三公司瀑布
    aidcBridge: {
      formula: "客户背书的 MW × 上架率 × 单 MW 收入/毛利 − 折旧 − 财务费用 → 扣非净利",
      companies: [
        { name: "润泽科技", figures: "AI 数据中心收入 25.10 亿元（占 44.24%）、毛利率 48.50%、上架率 >90%、累计交付 750MW；归母 50.50 亿 vs 扣非 19.01 亿",
          note: "唯一有直接利润锚点；必须用扣非口径。", drill: { title: "润泽科技利润桥", value: "扣非 19.01 亿元（归母 50.50 亿含不动产信托投资收益）",
            sub: "客户背书的 MW × 上架率 × 单 MW 毛利 − 折旧 − 财务费用。", source: "官方披露 · 2025 年报" } },
        { name: "奥飞数据", figures: "财务费用/收入 12.17%", note: "转型中，杠杆侵蚀利润。",
          drill: { title: "奥飞数据", value: "财务费用/收入 12.17%", sub: "转型期财务费用高企。", source: "官方披露 · 2025 年报" } },
        { name: "数据港", figures: "401MW 在运，智算收入占比仅 0.21%", note: "未来期权：目前贡献很小。",
          drill: { title: "数据港", value: "401MW 在运，智算收入占比 0.21%", sub: "传统批发型数据中心为主。", source: "官方披露 · 2025 年报" } },
      ],
    },

    // §10 内存周期曲线（涨幅收敛先于价格见顶）
    dramCycle: {
      points: [
        { quarter: "2026 Q1", change: "+93~98%", note: "" },
        { quarter: "2026 Q2", change: "+50~55%", note: "" },
        { quarter: "2026 Q3 预期", change: "+13~18%", note: "TrendForce（2026-07-10）预计合约价涨幅放缓" },
      ],
      note: "涨幅收敛先于价格见顶——周期中后段最早可跟踪信号。存储周期史上没有大块产能软着陆的先例。",
      drill: { title: "DRAM 合约价轨迹", value: "+93~98% → +50~55% → +13~18%（2026 Q3 预期）",
        sub: "周期红利进入中后段：长鑫利润定性为周期红利，非 HBM 稀缺利润。", source: "行业机构 · 2026-07-10" },
    },

    // §11 出口管制三情景 × 7 层彩色矩阵（基线列高亮）
    scenarios: {
      cols: ["收紧", "冻结（当前基线）", "放松"],
      baseline: 1,
      rows: [
        { layer: "NVIDIA/美系芯片", cells: [ "中国收入归零延长，转运围堵升级", "中国收入约零，非中需求消化", "部分回流，但份额已永久损失" ] },
        { layer: "国产算力芯片", cells: [ "最强催化：订单/流片/产能全加速", "按现有节奏兑现（海光预告已验证）", "边际利空，政策采购托底" ] },
        { layer: "高带宽内存/存储", cells: [ "长鑫 HBM 战略价值跳升", "长鑫样品到量产按节奏", "韩系放量，长鑫溢价弱化" ] },
        { layer: "光模块/PCB", cells: [ "基本不受影响（需求在海外）", "800G/1.6T 逻辑不变", "不变" ] },
        { layer: "模型层", cells: [ "中国模型获全球分发真空", "19 天下架作为先例记录", "出海竞争加剧" ] },
        { layer: "云与 AI 数据中心", cells: [ "国产算力采购占比要求强化（≥75% 口径原文未核验，标注待核）", "按现有建设与上架节奏", "边际利空" ] },
        { layer: "设备/材料", cells: [ "国产设备材料订单加速", "国产替代资本开支利润延续", "边际利空" ] },
      ],
      triggers: "B30A 放行→放松；管制扩到高带宽内存/零部件/第三国→收紧；模型层再次下架→收紧（模型层）；国产采购占比正式文件→收紧情景下国产链强化。",
      note: "不预测政策，只准备响应。北京对能耗效率（PUE）>1.35 的存量数据中心征差别电价（官方披露）。",
    },

    // §11 管制时间轴（六事件）
    exportTimeline: [
      { date: "2026-04-30", label: "对华高端直销归零", kind: "brk",
        drill: { title: "2026-04-30 · 直销归零", value: "NVIDIA 对华高端直销归零（黄仁勋口径）；B30A 未放行", sub: "", source: "管理层口径 · 2026-04-30" } },
      { date: "2026-05-31", label: "子公司指引（堵第三国绕道）", kind: "brk",
        drill: { title: "2026-05-31 · 子公司指引", value: "美国商务部工业安全局（BIS）指引扩展至受限国企业境外子公司", sub: "堵第三国绕道。", source: "官方披露 · 2026-05-31" } },
      { date: "2026-06-12→07-01", label: "模型层首例：全球下架 19 天", kind: "brk",
        drill: { title: "2026-06 · 模型层管制首例", value: "美商务部令 Anthropic 两个新模型全球下架，07-01 恢复，停售 19 天",
          sub: "另一美国旗舰模型被要求分阶段开放。'生产力单元的跨境结算'从此有了先例。", source: "官方披露 · 行业机构 · 2026-06-12" } },
      { date: "2026-07-07", label: "中国海关据报阻 H200 入境", kind: "brk",
        drill: { title: "2026-07-07 · 双向冻结", value: "中国海关据报指示 H200 不得入境",
          sub: "战略与国际研究中心（CSIS）转述。", source: "行业机构 · 2026-07-07" } },
      { date: "2026-07-14", label: "新监管行动信号", kind: "cur",
        drill: { title: "2026-07-14 · 酝酿中", value: "美商务部释放新监管行动信号", sub: "", source: "行业机构 · 2026-07-14" } },
      { date: "2026-07-17", label: "基线：双向冻结", kind: "cur",
        drill: { title: "2026-07-17 · 当前基线", value: "芯片层与模型层双向冻结是当前基线",
          sub: "管制已从芯片层扩到模型层，且双向化。", source: "官方披露 · 行业机构 · 2026-07-17" } },
    ],

    // §12 假说裁决对照矩阵（八架天平；蓝=已验证/琥珀=有证据有争议/灰=假说待裁决）
    verdictMatrix: {
      lead: "每条判断都附失效条件：以下指标一旦越线，对应结论即应重估。本报告数据截至 2026-07-17。",
      mustBeWrong: "本报告判断此处必有一错：前沿档按'用量 8 倍 + 价格持平'外推会得到不可能的收入——要么编程智能体用量增速下台阶，要么前沿档价格扛不住。两个方向的证据已在下面列出。",
      rows: [
        { id: "H1", hypothesis: "任务通胀使需求被系统性低估", strength: "已验证", chapter: "§1",
          bside: "浪费率大幅压缩（如 70%→20%）且有效需求涨幅低于约四成，总消耗下降" },
        { id: "H2", hypothesis: "计量战争赢家是混合制而非按结果计费", strength: "有证据有争议", chapter: "§2",
          bside: "按结果计费偏好持续过半、席位续费率崩坏" },
        { id: "H3", hypothesis: "前沿定价权真实但靠补贴，12–18 个月内转向按量", strength: "有证据有争议", chapter: "§3",
          bside: "旗舰毛利公开转正；或前沿档价格崩塌" },
        { id: "H4", hypothesis: "需求 3.94x vs 供给 2.85x，缺口温和收紧", strength: "有证据有争议（本报告测算）", chapter: "§5",
          bside: "中国模型服务增速砍半（结论翻转开关）；官方用量连续两季下台阶" },
        { id: "H5", hypothesis: "瓶颈接力到电力，资本无法速成", strength: "有证据有争议", chapter: "§6–§7",
          bside: "2028 缺口收敛测算兑现；PJM 拍卖降温；燃机交期缩短" },
        { id: "H6", hypothesis: "资本开支是黄橙灯的'投入大、赚得少'，不是泡沫", strength: "有证据有争议", chapter: "§8",
          bside: "GPU 租赁价与利用率双下行；超大云厂商下修 + 租赁商违约" },
        { id: "H7", hypothesis: "利润池 71.3% 上游化，模型层为负", strength: "有证据有争议（本报告测算快照，base 情景）", chapter: "§9",
          bside: "模型公司持续正现金流 + 上游价格下行同现" },
        { id: "H8", hypothesis: "中国利润在资本开支/国产替代链，模型/应用未证明", strength: "有证据有争议", chapter: "§10",
          bside: "模型/应用披露付费率/每用户平均收入/推理成本后毛利为正" },
      ],
    },

    // §12 反证触发条件面板（八条红线：人话标签 + 当前读数 + 阈值 + "越线即重估"后果句；静态条件句）
    triggers: [
      { label: "上游合同价、交期与库存", current: "高带宽内存 2026 售罄、2027 全订完；封装'严重供不应求'",
        threshold: "HBM 或先进封装的合同价转跌、交期缩短、库存上升（至少两类同现）", consequence: "上游稀缺利润重估为周期性风险",
        drill: { title: "红线 · 上游稀缺利润", value: "越线即重估：上游稀缺利润降级为周期性风险",
          sub: "已发生的并列事实：2026 年一季度起 HBM 每片晶圆收入已被普通服务器内存条反超。", source: "行业机构 · 2026-07-10" } },
      { label: "GPU 租赁价格与利用率", current: "H100 一年期租金 $2.35/GPU·小时（反弹 40%）；各代长约价全面上涨；现货约 $1.5–2/GPU·小时",
        threshold: "GPU 租赁价格与利用率同时趋势性下行", consequence: "新兴算力租赁商折旧压力重估",
        drill: { title: "红线 · 算力租赁商", value: "越线即重估：租赁商折旧与债务压力升级",
          sub: "长约涨 vs 现货跌的分化已在；CoreWeave 利息占收入 25.8%。", source: "媒体报道与访谈 · 券商研究 · 2026-04-06" } },
      { label: "在手订单 vs 云收入", current: "Google Cloud 在手订单 $462B；Microsoft 未开始租赁 $155.1B；Oracle 已签约未交付 $553B",
        threshold: "在手订单增长但云收入/AI 年化收入/毛利不同步", consequence: "资本开支回收可见性下调",
        drill: { title: "红线 · 资本开支回收", value: "越线即重估：订单簿不再是需求的硬证据",
          sub: "订单转收入放慢是第一个可观察信号。", source: "官方披露 · 截至 2026-07-17" } },
      { label: "AI 产品续费质量", current: "ServiceNow 续费率 97%；Agentforce 付费渗透约 6%",
        threshold: "AI 产品采用增长但续费率/年度合同额/毛利不改善", consequence: "应用层变现质量下调",
        drill: { title: "红线 · 应用层变现", value: "越线即重估：'收到钱'降级为一次性采用",
          sub: "渗透率个位数 + 单位毛利未证明是当前的脆弱组合。", source: "官方披露 · 券商研究 · 截至 2026-07-17" } },
      { label: "模型公司现金流", current: "OpenAI 2025 经营亏损 −$20.92B；Anthropic 年化收入 $47B（未经审计）",
        threshold: "OpenAI/Anthropic 到 2028–2029 仍无法证明正现金流", consequence: "全链回报率下调",
        drill: { title: "红线 · 模型层", value: "越线即重估：上游收入被解释为资本循环",
          sub: "反向反证：模型公司证明高毛利正现金流，则模型层利润留存强于预期。", source: "媒体报道与访谈 · 截至 2026-07-17" } },
      { label: "中国付费率与毛利", current: "豆包月活 3.45 亿、180 万亿 token/天；付费率/每用户平均收入/毛利未披露",
        threshold: "中国模型/应用量增但付费率/毛利不成立", consequence: "中国股东赢家判断下调",
        drill: { title: "红线 · 中国利润桥", value: "越线即重估：生态赢家不等于股东赢家",
          sub: "月活、token、下载量不能当利润证据。", source: "官方披露 · 截至 2026-07-17" } },
      { label: "token 用量 vs 任务收入", current: "Salesforce token 环比 +152% 快于任务量单位 +111%",
        threshold: "token 用量涨、任务完成与工作流收入不涨", consequence: "'降价释放利润'降级为'扩大基础设施消耗'",
        drill: { title: "红线 · 任务计量", value: "越线即重估：通胀的只是浪费",
          sub: "任务量单位口径曾扩围，边际汇率在漂移。", source: "官方披露 · 2026-05-27" } },
      { label: "中国模型服务一线增速（结论翻转开关）", current: "豆包同比 +10 倍；近 3 个月 +50%（年化约 5 倍）",
        threshold: "中国模型服务一线基准增速砍半（4.0x→2.0x）", consequence: "供需缺口结论翻转：需求 2.83x < 供给 2.85x，缺口缓解",
        drill: { title: "红线 · 缺口方向", value: "越线即重估：缺口叙事整体翻转",
          sub: "承重假设：对结论贡献最大的那个假设——它一动，结论就动。", source: "本报告测算 · 2026-07-17" } },
    ],

    // §13 方向地图（产业链五层 × 超配/中性/回避；哑铃两端电蓝、中间挤压段语义红）
    directionMap: {
      disclaimer: "本报告为研究分析，不构成投资建议；方向性判断不对应任何个股或代码。超配/低配 = 相对多配/少配的方向性判断。",
      layers: [
        { name: "硬约束上游（高带宽内存/先进封装/先进制程代工/电力设备与交付）", stance: "超配", chapter: "§6–§7",
          reason: "唯一资本无法速成的约束，订单可见度以年计；电力设备与交付链当前位置类似 2023 年的先进封装。",
          invalidate: "上游合同价转跌 + 交期缩短 → 稀缺利润交易结束，切向工作流软件与现金。" },
        { name: "云/调度层", stance: "中性", chapter: "§8–§9",
          reason: "需求真实但资本开支与折旧压力上行，分化加剧；回避资产负债表紧绷的二线云。",
          invalidate: "GPU 租赁价与利用率双下行 → 调度租整体下调。" },
        { name: "模型层", stance: "回避为主", chapter: "§9",
          reason: "收入高增但利润未证明；回避只靠补贴的订阅档与靠供应商融资循环的主体。",
          invalidate: "模型公司证明持续正现金流 → 哑铃中间段重估，应用层敞口上调。" },
        { name: "工作流软件（哑铃另一端）", stance: "超配", chapter: "§4",
          reason: "有数据、权限与分发入口，真正按任务收到钱且有续费证据者（单独定价的 AI 产品 + 高续费率）。",
          invalidate: "续费率/年度合同额/毛利不改善 → 变现质量下调。" },
        { name: "服务/组装代工", stance: "回避", chapter: "§10",
          reason: "只赚过手钱的组装与代工：收入高、利润薄、库存重。",
          invalidate: "出现自有稀缺环节卡位再评估。" },
      ],
      chinaNote: "中国侧超配：资本开支/国产替代供给链——光互连、高端 PCB、存储、设备材料，以及有客户背书的 AI 数据中心利润桥（上架率与单兆瓦利润可验证者）；回避'只有概念没有利润'的模型/应用股东敞口——在付费率与毛利被证明之前。",
      shiftConditions: [
        "上游合同价转跌 + 交期缩短 → 稀缺利润交易结束，从上游硬约束切向工作流软件与现金；",
        "中国模型服务增速砍半 → 缺口叙事翻转，全链降低杠杆敞口；",
        "超大云厂商资本开支指引下修 → 黄橙灯转红，回避高杠杆建设链与弱节点；",
        "模型公司证明持续正现金流 → 哑铃中间段重估，应用层敞口上调。",
      ],
    },

    // §13 情景→方向切换表（五情景 × 受益/受损 × 概率读数 × 易误判点）
    shiftTable: [
      { scenario: "半导体瓶颈延续", benefit: "硬约束在位者（高带宽内存/先进封装/先进制程代工）", harm: "云与模型层毛利受挤压",
        prob: "较高", pitfall: "把周期红利当永久稀缺" },
      { scenario: "通电速度成主瓶颈", benefit: "电力设备与交付链、自备电源与核电长期购电协议受益方", harm: "选址受限的云厂商与二线租赁商",
        prob: "中高", pitfall: "把发电成本当瓶颈——稀缺的是区域并网交付，不是发电" },
      { scenario: "回收压力提前暴露", benefit: "现金流强的超大云厂商、有续费证据的工作流软件", harm: "高杠杆新兴算力租赁商、项目债主体、供应商资金循环两端",
        prob: "中", pitfall: "把订单簿当现金——订单不等于回款" },
      { scenario: "降价放量成立", benefit: "走量档平台、应用分发与集成层", harm: "前沿档溢价叙事、靠补贴的订阅档",
        prob: "中低", pitfall: "忽视任务通胀对总量的对冲——单价降、单任务用量涨" },
      { scenario: "开源与自研芯片替代加速", benefit: "自研芯片生态、国产替代供给链", harm: "通用 GPU 溢价、单一供应商依赖",
        prob: "中", pitfall: "低估软件生态迁移成本" },
    ],

    // §13 六条结论徽章卡（每条带强度徽章）
    conclusions: [
      { id: 1, strength: "方向已验证", text: "利润当前在上游结算，呈哑铃结构：上游稀缺环节与下游工作流软件两头强，中间的通用包装层（模型转售、单功能壳层）最受挤压。" },
      { id: 2, strength: "有证据有争议", text: "稀缺利润会迁移且强周期化：电力设备与交付链的当前位置，类似 2023 年的先进封装——但租金随棒移交均值回归，上游赢家不是永久赢家。" },
      { id: 3, strength: "有证据有争议", text: "任务计量正在重排定价权：混合制计费 + 前沿档溢价是当前赢家结构；按结果计费尚未逆转席位制。" },
      { id: 4, strength: "有证据有争议", text: "资金侧是黄橙灯的'投入大、赚得少'，回本未被证明；最脆弱处在 OpenAI 与供应商之间的资金循环、高杠杆算力租赁商与 Oracle，不在四家超大云厂商。" },
      { id: 5, strength: "有证据有争议", text: "中国链已验证的股东利润在资本开支/国产替代供给链与有客户背书的 AI 数据中心；模型/应用层股东利润未被证明——生态赢家不等于股东赢家。" },
      { id: 6, strength: "有证据有争议", text: "最大的风险不是'泡沫'，是斜率：资本开支增速（约翻倍）远高于经营现金流增速（约两三成），二者终将收敛——收敛的方式（软着陆还是急刹车）决定所有方向的保质期。" },
    ],

    // 引文卡（五段式 + 出处；未逐字核验者一律转述、不带引号）
    quotes: {
      zhou: { quote: "查个天气要消耗上千万 token，做个 PPT 要上亿——很多消耗是没有道理的。", quote_cn: "",
        speaker_or_source: "周鸿祎（360 集团创始人）", published_at: "2026-06-24",
        context_note: "谈企业落地 AI 时的算力浪费（据公开演讲内容转述，未经逐字核验，不带引号）。",
        why_it_matters: "反方证据：任务通胀中有相当比例是可压缩的浪费——挂在浪费率段。",
        source_url: "", verbatim: false },
      github: { quote: "GitHub 官方解释改制理由：轻量问答与数小时的长任务同价，旧订阅模式难以为继。", quote_cn: "",
        speaker_or_source: "GitHub 官方说明（转述）", published_at: "2026-04-27",
        context_note: "Copilot 订阅改按 AI 点数计费的公告语境（转述，未逐字核验，不带引号）。",
        why_it_matters: "计量战争的正方：按量计费的官方理由——'一个任务'该值多少钱，厂商自己也算不过来。",
        source_url: "", verbatim: false },
      techcrunch: { quote: "TechCrunch 评 GPT-5 定价：低到可能挑起价格战。", quote_cn: "",
        speaker_or_source: "TechCrunch（转述）", published_at: "2025-08",
        context_note: "GPT-5 以 $1.25/$10 发布当周的评论（转述，未经逐字核验）。",
        why_it_matters: "谷底见证：市场一度认为模型价格崩了——此后旗舰价 V 形反转。",
        source_url: "", verbatim: false },
      wei: { quote: "severely supply-constrained", quote_cn: "严重供不应求（中文译述与语境为意译：后段封装已成为限制客户成长的瓶颈）",
        speaker_or_source: "魏哲家（台积电董事长），2026-07-16 法说会", published_at: "2026-07-16",
        context_note: "原文仅英文短语经坐实；中文译述与语境为意译。法说会 = 上市公司每季度向投资者说明业绩的会议。",
        why_it_matters: "第三棒现状的官方确认：封装产能追不上客户成长。",
        source_url: "", verbatim: true },
      nadella: { quote: "warm shells", quote_cn: "没有通了电可以插的机房（芯片躺在库存里插不上电——中文为意译）",
        speaker_or_source: "萨提亚·纳德拉（微软 CEO），BG2 播客", published_at: "2025-11（中旬）",
        context_note: "原文英文短语；中文译述为意译。",
        why_it_matters: "第四棒电力的标志事件：芯片瓶颈让位于电力瓶颈的公开承认。",
        source_url: "", verbatim: true },
      strazik: { quote: "GE Vernova CEO 斯特拉齐克称，燃机并非真正的卡点和瓶颈，瓶颈在工程总包、许可与燃料。", quote_cn: "",
        speaker_or_source: "GE Vernova CEO（转述）", published_at: "2026-04-22",
        context_note: "财报电话会议语境（转述，未经逐字核验，不带引号）。",
        why_it_matters: "反方卡，与纳德拉卡同框：设备商自己认为瓶颈在交付链下游，不在设备——A 面 B 面并列的示范位。",
        source_url: "", verbatim: false },
      huang: { quote: "黄仁勋称，对 OpenAI 的这笔投资很可能是最后一笔。", quote_cn: "",
        speaker_or_source: "黄仁勋（NVIDIA CEO，中译转述）", published_at: "2026-03-04",
        context_note: "$100B 意向书 2026-02 作废、转为 $30B 股权之后（中译转述，未经逐字核验）。",
        why_it_matters: "供应商融资转向信号：最大的供应商开始收缩对客户的资金循环。",
        source_url: "", verbatim: false },
      gold: { quote: "模型收入足以支撑'需求真实'，但不足以支撑'模型层已拿走主要利润池'。", quote_cn: "",
        speaker_or_source: "本报告", published_at: "2026-07-17",
        context_note: "§9 利润池瀑布章题眼落点。",
        why_it_matters: "全报告金句卡：需求真实性与利润留存是两回事。",
        source_url: "", verbatim: true },
    },

    // 行内来源钮字典（fact → 级别 · 日期）
    sources: {
      gapRatio: { fact: "供需缺口比 0.70→0.97（base 情景），走廊 0.34–2.27", cite: "本报告测算 · 2026-07-17" },
      demandSupply: { fact: "需求年化增速 3.94x vs 供给 2.85x（base 情景）", cite: "本报告测算 · 2026-07-17" },
      profitShare: { fact: "利润池半导体份额 71.3%（base 情景）", cite: "本报告测算 · 2026-07-17" },
      revPool: { fact: "推理收入池 $326B（base 情景，走廊 $241B–$411B）", cite: "本报告测算 · 2026-07-17" },
      capexGuide: { fact: "四家 2026 年资本开支指引合计 $695–725B", cite: "券商研究 · 2026-07-17" },
      capex2025: { fact: "四家 2025 年资本开支合计 $359.9B（+64%，公司披露现金口径）", cite: "官方披露 · 截至 2026-07-17" },
      doubao: { fact: "豆包日调用量 180T/天，同比 +10 倍；近 3 个月 +50%（年化约 5 倍）", cite: "官方披露 · 2026-06-23" },
      googleTokens: { fact: "Google 全平台 token 处理量 3.2Q/月，同比约 7 倍（锚点在减速）", cite: "官方披露 · 2026-05" },
      anthropicArr: { fact: "Anthropic 年化收入 $47B（17 个月 47 倍，管理层口径未经审计）", cite: "媒体报道与访谈 · 2026-05" },
      sfExchange: { fact: "7,526 token/任务量单位（28.6 万亿 token / 38 亿任务量单位，累计口径）", cite: "官方披露 · 2026-05-27" },
      agentforceArr: { fact: "Agentforce 年化收入 $1.2B（同比 +205%）", cite: "官方披露 · 2026-05-27" },
      openaiLoss: { fact: "OpenAI 2025 年经营亏损 −$20.92B（审计报道口径）", cite: "媒体报道与访谈 · 2026-02" },
      pjmGap: { fact: "PJM 2028/29 年度容量缺口 6,831MW，连续第四次触顶", cite: "官方披露 · 2026-07-14" },
      pjmTrack: { fact: "PJM 清算价 $28.92→$269.92（+833%）→$333.44（累计 +1,053%）", cite: "官方披露 · 2026-07-14" },
      tsmcCowos: { fact: "台积电后段封装'severely supply-constrained'，资本开支上调至 $60–64B", cite: "官方披露 · 2026-07-16" },
      h100Markup: { fact: "H100 终端价 $25,000–30,000 vs 物料成本约 $3,320，加价约 7.5–9 倍", cite: "券商研究 · 2023-08" },
      k3Price: { fact: "Kimi K3 定价 $3/$15 = K2 输入价的 5 倍", cite: "官方披露 · 2026-07-17" },
      gpt5Floor: { fact: "GPT-5 发布价 $1.25/$10 为旗舰谷底", cite: "官方披露 · 2025-08" },
      bond159: { fact: "2026 年迄今五大云厂商发债 $159B（同比 +47%）", cite: "行业机构 · 2026-06" },
      coreweaveCover: { fact: "CoreWeave 在手订单 $99.4B = 47.8 倍季度收入", cite: "官方披露 · 截至 2026-07-17" },
      aliAi: { fact: "阿里云 AI 产品收入 89.71 亿元/季，AI 年化收入 >358 亿元", cite: "官方披露 · 2026-05" },
      cxmtIpo: { fact: "长鑫科技为截至 2026-07 科创板募资规模最大的 IPO", cite: "官方披露 · 2026-07-16" },
      nvdaDc: { fact: "NVIDIA 数据中心收入 $75.2B/季（+92%，FY2027 Q1）", cite: "官方披露 · 2026-05" },
      subsidy70x: { fact: "$200/月订阅拉满使用 ≈ $14,000/月 API 等效（理论上限 70 倍）", cite: "媒体报道与访谈 · 2026-06" },
    },

    // 方法边界章：口径、来源与已知局限
    method: {
      methodNote: "需求侧测算不采用参数正推法——需求按月变化、用量呈幂律分布，单点正推不可靠。本报告改用『已披露锚点 × 情景区间』方法，只给区间、不给单点，全部锚点可点击查看到带日期的公开出处。",
      sourceNote: "本报告全部图表数字出自同一份数据底稿，截至 2026-07-17，均为公开信息或基于公开信息的测算。图中任一数字可点击查看口径与带日期的出处。仅供参考，不构成投资建议。",
      levels: [
        { name: "官方披露", rule: "可当事实，带日期。公司季报/年报、官方定价页、官方路线图、拍卖结果、官方机构统计、法说会。" },
        { name: "管理层口径", rule: "注明'管理层口径'。AI 年化收入、在手订单定义等。" },
        { name: "券商研究", rule: "保留区间与冲突，不收敛成单点；单一来源测算单独标注。" },
        { name: "媒体报道与访谈", rule: "注明媒体与日期；泄露/访谈型数字不得写成已验证事实；私营公司数字统一标'媒体转述/审计报道口径'。" },
        { name: "本报告测算", rule: "报区间不报点值，附敏感性与结论翻转开关。" },
      ],
      limits: [
        "供给测算未按模型档位拆分服务速率；",
        "中国模型服务的有效价格偏贵，收入池区间可能偏高 1.5–2 倍；",
        "Anthropic 年化收入与云厂商分成口径未拆；",
        "编程智能体周活'近千万'来自匿名社交账号泄露，未经核验；",
        "行业标准性能测试数据仅作上界。",
      ],
    },
  };
})();
